### ISSUE TITLE
In the RISC-V platform, there is a risk of integer overflow.

### ISSUE THREAD

**Issue by CtrlZ233** [seL4/seL4#1002]
https://github.com/seL4/seL4/blob/ec170f4c21cdd6c9e163c0da681c912a52b97b8a/src/kernel/boot.c#L682

In the seL4test project, using the configuration parameter for the Spike architecture, this line of code caused an integer overflow.

Printed code and results are shown below：
```c
   if (start < CONFIG_PADDR_USER_DEVICE_TOP) {
        region_t reg = paddr_to_pptr_reg((p_region_t) {
            start, CONFIG_PADDR_USER_DEVICE_TOP
        });
        printf("untyped_region: 0x%lx ... 0x%lx\n", reg.start, reg.end);
        if (!create_untypeds_for_region(root_cnode_cap, true, reg, first_untyped_slot)) {
            printf("ERROR: creation of untypeds for top device region"
                   " [%"SEL4_PRIx_word"..%"SEL4_PRIx_word"] failed\n",
                   reg.start, reg.end);
            return false;
        }
    }
```

```
untyped_region: 0xffffffc17ff00000 ... 0x4000000000
```

**Comment by lsf37** [comment]
Thanks for spotting that. While `CONFIG_PADDR_USER_DEVICE_TOP ` and the other region data that is input to these functions are trusted input, it would still be good to sanity check it and fail early here instead of producing the overflow.

**Comment by lsf37** [comment]
Ok, so looking further at this (thanks to @Ivan-Velickovic for pointing me in this direction), the overflow as such is actually completely fine, because we are trying to create device Untypeds which don't have to have valid pointers, they just need to store regions.

The only problem is that we don't want one contiguous region `0xffffffc17ff00000 ... 0x4000000000`. I think it should be creating two regions `0xffffffc17ff00000 ... 0xffffffffffffffff` and `0x0 ... 0x4000000000`. @kent-mcleod am I seeing this correctly?

**Comment by lsf37** [comment]
Sorry, should have remembered this from the beginning: this is in fact completely fine, because the function this is passed to will deal gracefully with such regions and divide them up into aligned non-overflowing parts.

The thing that is missing is documentation for this fact.

**Comment by axel-h** [comment]
Looks like we've been there already, see https://github.com/seL4/seL4/issues/389

**Comment by CtrlZ233** [comment]
> Looks like we've been there already, see #389

Okay, I think I understand what happened. Thanks.
