### ISSUE TITLE
How to crosslink to specific sections in the seL4 manual?

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/seL4#1087]
Currently there is a URL to the current version of the manual: http://sel4.systems/Info/Docs/seL4-manual-latest.pdf

Often it would be useful to be able to send someone a URL to a section within the manual, eg 6.1 Threads, however I don't think this is possible currently.

A solution to this could be html outputs of the manual for each released version hosted under https://docs.sel4.systems.

**Comment by ratmice** [comment]
It seems that this does work for the pdf, one can get a list of anchors (called named destinations in pdf land) via `pdfinfo -dests seL4-manual-latest.pdf`. e.g. [chapter 3](https://sel4.systems/Info/Docs/seL4-manual-latest.pdf#chapter.3) or [page 100](https://sel4.systems/Info/Docs/seL4-manual-latest.pdf#page=100) there are perhaps some latex packages that could be used to give them nicer names than the current ones that I imagine are autogenerated (I'm not currently familiar with any of these packages however).

Anyhow it is perhaps (or seems to me like) less work involved in expanding the anchors available in the current pdf output than something involving a new output format.

**Comment by kent-mcleod** [comment]
Oh thanks, it's possible to copy links to each section from the table-of-contents view in my browsers PDF viewer too: https://sel4.systems/Info/Docs/seL4-manual-latest.pdf#subsection.3.3.2

**Comment by ratmice** [comment]
Well, let me know or reopen if you feel like anything there is anything could be improved.  I would happily look into it.

**Comment by lsf37** [comment]
I think it'd be nice to have a html version of the manual in general, e.g. for people who want to read on mobile or tablets, but maybe not super high priority at the moment.

**Comment by ratmice** [comment]
I did a cursory look at building the manual with various tex -> html tools

* latex2html worked without changes, but the output looks rather 
* tex4ht had nicer output but required [hacks](https://github.com/ratmice/seL4/tree/tex4ht-manual) or a newer tex4ht than my distro has

In addition I tried tectonic but their html output is a work in progress, and was unsuccessful.

**Comment by ratmice** [comment]
> The other option would be to (semi-manually) convert the manual to md or rst or similar once and generate different formats from there. I had a look at that a while ago, it would not be a small project because the manual currently uses a bunch of LaTeX features that are not present in md or rst, but it would probably make it more accessible overall.

I'm not yet intimately familiar with which the parts of the manual that require LaTeX you are referring to and if they are systemic,
or isolated tables/figures and so on, so depending on what is required the following may not be an option.  In a project I worked on we rendered latex snippets in code blocks via

````
```latex render
figures and stuff.
```
````

It doesn't get us any closer to new output formats, but could incrementally minimize the latex conversion required, at the expense of a custom markdown parser capable of rendering LaTeX snippets.

This is the approach I took for a "literate theorem proving" environment where having at least some inline LaTeX seems crucial.
djot includes first class support for attributes to markdown making it better at conveying attributes like *render* rather than including it as syntax highlighted code, but you can pull it off with just markdown too as described.

Anyhow, here are some examples of that style. Where the markdown embedded in `/-- markdown comments --/` within proof source... I'm not sure if that kind of approach would interests you at all, but it seems like an option.

https://gist.github.com/ratmice/29b869369ec02232b80dce3498a4c0b4#file-examples-pdf
https://github.com/ratmice/lumpy-leandoc/blob/master/examples/modus.lean
