### ISSUE TITLE
AArch64: 4k user page PTEs appear to be created incorrectly

### ISSUE THREAD

**Issue by Xaphiosis** [seL4/seL4#1110]
While working on proof setup for C refinement for AArch64, I had to write a spec for `makeUserPage` (which is also interestingly not named makeUserPTE like on other platforms). The function contains this interesting block (`src/arch/arm/64/kernel/vspace.c`):

```
    /* If The target page size is 4k, then really pte_pte_4k_page_new() should be used
       but instead we just update the type manually after using pte_pte_page_new(). */
    if (page_size == ARMSmallPage) {
        ret.words[0] |= 0x3;
    }
```
("just", haha)

From a type safety perspective, this kind of re-enactment of `reinterpret_cast` on the bitfield generator is not good, and from the verification side we strongly suggest avoiding it. I tried to prove that taking a `pte_page` and ORing 3 will result in a `pte_4k_page` with identical parameters and ended up with this unprovable situation:
```
pte_get_tag pte = SCAST(32 signed → 64) pte_pte_page 
⟹ pte_get_tag (pte_C.words_C_update (λv. Arrays.update v 0 (v.[0] || 3)) pte) =
      SCAST(32 signed → 64) pte_pte_4k_page
```
This indicates that there is no way one can take a word that is tagged as a pte_page, OR it with 3 and have it be interpreted as a pte_4k_page.

The tags are explained in `structures.bf` with:
```
-- There are two page type fields because the 4k page size
-- uses a different hardware encoding. We use bit 58
-- which is reserved for software use to encode this
-- difference in the tag for these types.
tagged_union pte pte_type(pte_hw_type, pte_sw_type) {
    tag pte_table               (3, 0)
    tag pte_page                (1, 0)
    tag pte_4k_page             (3, 1)
    tag pte_invalid             (0, 0)
}
```

So for a pte_page we need bit 0 set, and for a 4k page we need bits 58,1,0 set. Note that the integer 3 does not contain bit 58.

Unless there is some other workaround that magically fixes this issue at some other location, it means that no user pages on AArch64 are being placed in the page table as 4k pages. Not sure what this means when running on actual hardware.

I have assigned myself to this issue as I want to rewrite and rename this function to avoid its current issues of being annoying to find, understand and reason about, additionally avoiding bypassing the bitfield generator with that tag cast that also happens to be wrong. Will aim for a PR tomorrow.

**Comment by kent-mcleod** [comment]
> which is also interestingly not named makeUserPTE like on other platforms

At the time I probably felt that makeUserPTE was a bad name for aarch64, where because of the single page table object, a PTE (page table entry) can either be a page or another page table.  Because said function only creates page entries, I renamed it to makeUserPages.

RISC-V just has a single pte type for both pages and other PTEs. Why doesn't it have a separate type for page tables and pages?

> So for a pte_page we need bit 0 set, and for a 4k page we need bits 58,1,0 set. Note that the integer 3 does not contain bit 58.

I think based on the comment ("we just update the type manually"), bit 58 should be being set here. I don't think there's anywhere in the code that reinterprets the type of a last level page other than this one that came up in review: https://github.com/seL4/seL4/pull/801/files#r1282570629. Maybe you can rewrite makeUserPage to inline the differences for the armPageCacheable bit and just have a branch on the page size. I think at the time I was trying to copy all the code out multiple times...

**Comment by Xaphiosis** [comment]
Thanks for the fast reply!

I can keep the name if you like, but it makes a PTE, not a page :/

Yes, the goal is to collect the common fields in local vars and then branch on the page size for invoking the bitfield generator `_new` functions.

So, er, does this mean bug confirmed  ("bit 58 should be being set")? I was expecting this would have issues on hardware if the PTEs were mis-tagged in the PTs and TLB and would've been discovered before I got my hands on it.

**Comment by Indanz** [comment]
Bits 55:58 are reserved for software use, which means the hardware won't look at them and seL4 can use them however it wants. Not setting bit 58 is only a problem if seL4 checks bit 58 somewhere else to see what type of entry it is.

The current software doesn't seem to look at either the sw or hw types, so not sure why it's done. Could be useful for debugging perhaps, but it seems seL4 itself doesn't need this information in the pte entry itself.

**Comment by Xaphiosis** [comment]
If that's the case, then why do we have two different types of Page PTEs? I was under the impression that the hardware required it. @lsf37 do you recall from when you were adding the differentiation to the specs?

**Comment by Indanz** [comment]
For large pages the PTE is configured as a block with bit 1 set to zero, while normal 4k pages have bit 1 set to 1. Otherwise the format seems to be exactly the same. See:

https://armv8-ref.codingbelief.com/en/chapter_d4/d43_1_vmsav8-64_translation_table_descriptor_formats.html
https://armv8-ref.codingbelief.com/en/chapter_d4/d43_2_armv8_translation_table_level_3_descriptor_formats.html

I would use the same type for both large pages and 4k pages.

**Comment by Xaphiosis** [comment]
I'll remove the "bug" label then, and will update the function so it fits with the current design.
However, I'm still puzzled why we have the 4k distinction. The page table / vsroot I understand because the top level page table size is different. 4k pages are only allowed at the bottom-most level, but not sure now whether and why that lead to the page PTE / 4k page PTE distinction in object types.

The comment in structures.bf says
```
-- There are two page type fields because the 4k page size
-- uses a different hardware encoding.
```
But as far as I can tell the `block pte_page` and `block pte_4k_page` specs in `structures.bf` are the same.
Really hoping there was some good reason for this.

**Comment by lsf37** [comment]
I've re-added the bug label, because it is definitely a bug. seL4 uses the sw bit 58 and while not setting it here will not confuse the hardware (the hw will map the page correctly), but it will confuse seL4 later. In particular, the encoding seL4 uses is:

```
-- There are two page type fields because the 4k page size
-- uses a different hardware encoding. We use bit 58
-- which is reserved for software use to encode this
-- difference in the tag for these types.
tagged_union pte pte_type(pte_hw_type, pte_sw_type) {
    tag pte_table               (3, 0)
    tag pte_page                (1, 0)
    tag pte_4k_page             (3, 1)
    tag pte_invalid             (0, 0)
}
```

We should probably add a bit to the comment what exactly is going on: seL4 needs to be able to decode a PTE without first walking the entire table, but the hardware encoding for a table pointer and a 4k page are equal (both hw bits set). Which kind of PTE it is can only be determined by knowing at which level the PTE is in the table structure (if it's at the bottom it's a 4k page, otherwise it's a table PTE). To easily distinguish that without needing a walk, we are using the sw bit 58 to make the encoding independent of the level.

It could be that this particular bug will not manifest in misbehaviour, because it will only ever add the wrong encoding at the bottom level where a PT walk would not be able to continue anyway. But all of that depends a lot on the order in which seL4 checks the PTE type or if it makes other decisions before that etc.

In any case, the way Raf is proposing to rewrite the function, the encoding problem will disappear and be handled by the bitfield generator.

**Comment by Xaphiosis** [comment]
Ok, that does make sense, and also makes sense why we didn't notice any broken behaviour. I have a preliminary version, but need to make sure the C parser vcg likes it, which will take a while.
