### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for seL4

### ISSUE THREAD

**Issue by wangyuliu** [seL4/seL4#1136]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, the tool may have an average estimate of various architecture porting efforts.My focus is on the overall workload and difficulty of transplantation in the past and future,even if a project has already been ported.As part of my dataset, I have collected the **seL4** project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be moderate, with a moderate amount of code related to the CPU architecture in the project,such as assembly code.  Is this assessment accurate?Do you  have any opinions on personnel allocation and consumption time？ I look forward to your help and response.

**Comment by Indanz** [comment]
Hello @wangyuliu, questions like these are better asked on the [mailing list](https://lists.sel4.systems/postorius/lists/devel.sel4.systems/).

I haven't ported seL4, so can't answer you specific question. I would just like to point our that looking at the number of architecture specific lines of code is not a good measure for porting complexity. That is, there is a difference between the complexity of a port and the amount of work it requires. It can be a lot of simple work, or it can be very little, but complex work, or anything in between. I don't think you can see from the end result how many hidden hours were spend porting.

I will close this issue now, because people that subscribe to new issues will have seen it and can still reply (but those people also subscribe to the mailing list).
