### ISSUE TITLE
some symbols in c file is not include correctly

### ISSUE THREAD

**Issue by mttbx** [seL4/seL4#1215]
I find that the kernel is preprocessed to be a single c file then use that file to compile. I want to recompile the kernel by my way. So I change the project to compile the kernel by file. Unfortunately, the inclusion is chaotic. some symbols in c file is not include correctly. For an example:
`src/kernel/thread.c:141:5: error: implicit declaration of function 'reply_remove' [-Werror=implicit-function-declaration]`
There's a lot of errors like this. Is it on purpose? If not, I think it's better to correct this.
Besides, I find out that the symbol naming convention is chaotic too.

**Comment by Indanz** [comment]
No, it's not on purpose, it's just sloppy. Problems like these are hidden because everything is combined into one file. If there was a config option to disable it it would be a lot easier to find and fix these errors.

**Comment by mttbx** [comment]
This is meaningful. I think somebody more familar with the sel4 should do this. Known the structure of the project can helps a lot. So he can figure out which header files should be included indeed.

**Comment by Indanz** [comment]
Problem is, it's a very low priority thing, so no one gets to it. Definitions can be found with `ctags` or `git grep`. If you care about this, you will need to put effort into it yourself.

I prefer snake_case myself, but renaming everything because it's not to your liking is a very rude thing to do.

seL4 has coding conventions, they're documented [here](https://docs.sel4.systems/processes/style-guide.html#naming-of-symbols-variables-types-and-type-aliases-typedef). Style is being checked I believe, it's one of the CI actions.

**Comment by mttbx** [comment]
Alright, if anybody is interested in this, reopen it.
