### ISSUE TITLE
Why is `KernelArmVtimerUpdateVOffset` global?

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/seL4#1306]
Is there a reason the kernel configuration option `KernelArmVtimerUpdateVOffset` is set globally, e.g for every vCPU in the system rather than being a per-vCPU configuration at runtime?

It seems like this kind of policy would depend on the guest and hence seems weird to be a global configuration.

**Comment by JorgeMVP** [comment]
@Ivan-Velickovic interesting topic. I think this offset depends on what kind of notion we want to give to the guest OSes. Real (Absolut) or Virtual (Relative) time.

I don't know yet any solution that supports different configurations for different vCPUs. I'd be interested to know which problem did you get when setting this flag to true.

Thanks

**Comment by Indanz** [comment]
> I'd be interested to know which problem did you get when setting this flag to true.

The problem you get is that all timing is messed up in the guest, except if it uses 100% cpu and nothing else runs on the same core.

I guess the idea of enabling `KernelArmVtimerUpdateVOffset` by default is that the guest doesn't get any timing info from the rest of the system, so for minimal infoflow "security" reasons. However, as it breaks normal timekeeping too, it renders such guests mostly unsuitable for real-world usages.

**Comment by Ivan-Velickovic** [comment]
> I'd be interested to know which problem did you get when setting this flag to true.

What Indan said pretty much. If you do something like networking in a guest or anything that is remotely time sensitive the guest becomes pretty useless.

> guest doesn't get any timing info from the rest of the system, so for minimal infoflow "security" reasons

Makes sense, although I would expect being able to choose the policy for a particular vCPU.

**Comment by lsf37** [comment]
> > guest doesn't get any timing info from the rest of the system, so for minimal infoflow "security" reasons
> 
> Makes sense, although I would expect being able to choose the policy for a particular vCPU.

If you care about the timing issue, you'd probably want this to be enforceable on at least a sub-system level, though. If it is something you can set with an individual TCB or VCPU cap, any subsystem that can create objects can set whatever it likes.

I guess you could demand the presence of a different (maybe global) cap that authorises breaking that timing property.

But I'm not sure this was for security. I thought the problem was that there are guests that can't deal with clocks that jump randomly by large amounts. @kent-mcleod do you have any memory of this?

**Comment by Ivan-Velickovic** [comment]
> But I'm not sure this was for security. I thought the problem was that there are guests that can't deal with clocks that jump randomly by large amounts. @kent-mcleod do you have any memory of this?

I remember trying to going through the commit/PR history and couldn't find the exact motivation.

**Comment by kent-mcleod** [comment]
Before the config option was added the kernel wouldn't update the VOffset register and so the Virtual counter would be synchronized with the physical time stream. We added the config option once we started supporting projects that had multiple guest VCPUs sharing a single core.  At the time it seemed like a fairly important requirement that the clock source the guest was using for measuring how much vCPU time each user task was getting should only run while the vcpu was active. Linux guest tasks would get their time stolen by other tasks running in a different VCPU. Enabling this was only something that the kernel could do because it is responsible for context switching VCPU threads. We added the config option to preserve the old behavior and to support the new behavior. I recall that at the time we had projects that involved the multiple vcpu functionality + verified kernels and so we were also trying to support this functionality while minimizing verification changes. So far the virtualization use cases haven't needed a different policy for each VCPU and a global policy has been sufficient.

**Comment by Ivan-Velickovic** [comment]
Cool, that answers my question, thanks @kent-mcleod.

**Comment by lsf37** [comment]
Not sure if that helps with any future decisions, but for what it's worth, I'm planning to support both options in the verified kernel in the future as part of making the proofs more resilient against config changes.

**Comment by Ivan-Velickovic** [comment]
> Not sure if that helps with any future decisions, but for what it's worth, I'm planning to support both options in the verified kernel in the future as part of making the proofs more resilient against config changes.

Good to know.
