### ISSUE TITLE
Security & Safety Criticality

### ISSUE THREAD

**Issue by blackqbit** [seL4/seL4#203]
Hello.
i have a question:
support Sel4 security and safety critical certificate for avionic systems?

- DO-178
- MILS
- ...

**Comment by lsf37** [comment]
The kernel itself is not certified according to any of these standards, but it would very likely support (or exceed) the functionality and level of safety/security most of these standards need.

The problem is less whether it has the right level of safety, more whether it has actually gone through the process, which tends to be expensive. Depending on the standard, formal verification will help in varying degrees. In [DO178-C](https://en.wikipedia.org/wiki/DO-178C) some of the process can be satisfied by formal proofs (details in DO-333). 

Most standards don't allow certification of a kernel in isolation, but certify full systems, e.g. a plane. In general there would be interest on our side to help someone through a certification process with seL4 for the right level of funding.
