### ISSUE TITLE
ksDomainTime and MCS

### ISSUE THREAD

**Issue by lsf37** [seL4/seL4#226]
We've encountered a few issues in the MCS verification in combination with the domain scheduler. In particular, for the domain scheduler to work (not crash), we need to know that `0 < ksDomainTime` at kernel exit. In the MCS kernel, we probably want this to be `MIN_BUDGET <= ksDomainTime`.

## Issues
 1) `SchedControlConfigure` calls [`commitTime`](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/src/object/schedcontrol.c#L35), which decreases the domain time. This is inside a `perform` function which in the vanilla kernel leaves `ksDomainTime` untouched. Changing the fact that `perform*` doesn't touch `ksDomainTime` would require fairly large proof effort (this just happened to be true in the vanilla kernel, but the proof now relies on it).

 2) in [schedule](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/src/kernel/thread.c#L343), we check for domain expiry in [`scheduleChooseNewThread`](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/src/kernel/thread.c#L335), or know from preconditions that `ksDomainTime > 0`, but after the `scheduleChooseNewThread` operation, we call [`switchSchedContext`](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/src/kernel/thread.c#L396), which potentially calls `commitTime` (if `ksReprogram` is true), which subtracts `ksConsumed` from `ksDomainTime`, but we are in a new domain already, and we don't know that `ksConsumed < ksDomainTime`. The domain switch should come after the sched context switch. 

 3) more generally, `commitTime` does not know without further assumptions that [`ksDomainTime -= ksConsumed`](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/include/kernel/thread.h#L151) will not underflow.

4) the [`assert(ksDomainTime - NODE_STATE(ksConsumed) >= MIN_BUDGET)`](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/include/kernel/thread.h#L150) in `commitTime` does not look correct. If that property is intended, we need to set the interrupt earlier and should check for MIN_BUDGET instead of 0 in domain expiry (as `isCurDomainExpired` does, but it is not called in e.g. `scheduleChooseNewThread`).

## Proposed fixes:

 1) This may be fixable with a more complex proof, but for finishing the verification now I would prefer to forbid `SchedControlConfigure` on the current SC instead. If this turns out to be an actual annoyance for user-level, happy to revisit this in Nov.

 2) I think all that is needed is moving
   ```
    if (ksDomainTime == 0) {
        nextDomain();
    }
   ```
   from `scheduleChooseNewThread` to `switchSchedContext`. The test for `0` is likely wrong, it should probably be calling `isCurDomainExpired` instead.

 3) I propose that we artificially cut off `ksDomainTime` at 0 or MIN_BUDGET, i.e. `ksDomainTime = MIN(0, ksDomainTime-ksConsumed`.  We do know that we set the next timer interrupt such that it fires before too much time is up -- we set
   ```
next_interrupt = MIN(next_interrupt, NODE_STATE(ksCurTime) + ksDomainTime);
   ```
  in [`setNextInterrupt`](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/src/kernel/thread.c#L566), but I don't think we have any explicit assumptions about the timer hardware being correct in that sense. We have the concept of `TIMER_PRECISION`, but if that is even slightly off, we will get assertion failures for short domain times in debug configs or underflow in non-debug configs. I would leave in the assertion so that in debugging we can figure out if it happens, but use the above to turn the massive underflow into a small accounting error instead. Ideally, the production kernel would signal such situations to a monitor process or similar, but that is a change for after this verification.

4) I'm not sure about this one. It doesn't have any functional correctness impact, but it looks like we should adjust the interrupt calculation [here](https://github.com/seL4/seL4/blob/d989d2b85c2608f268aabd77bfb3ef3c6829b567/src/kernel/thread.c#L566).

**Comment by lsf37** [comment]
@pingerino before I prepare a patch for this, do these make sense from your side?

I'm not sure if afterwards MCS and domain schedule fully integrate, but at least there don't seem to be any other functional correctness issues between the two.

**Comment by pingerino** [comment]
Thanks for the very clear writeup!!

Using MCS + domain schedule is ... interesting and I didn't explore it much. I did try to make sure it was functionally correct. However the domain scheduler already lacks test coverage and I didn't make it any better.  

**First addressing the problem:**

The scheduler for threads assumes that the kernel checks on entry that if any operation were to run out of time and bill a thread, we simulate a tick at this point. This should be the same approach we take for switching domains. At the start of the kernel we should already know that commitTime won't impact scheduling, and if it will we should be ticking, not doing anything else. 

We do not have any explicit assumptions about timer correctness. 

I'm not sure MIN_BUDGET makes sense for domains. Because threads can block in the kernel, we need to make sure they have enough budget when they block in an IPC queue to be charged the time from kernel entry to the time they exit the kernel when they wake up, *as well as* the time to get into the IPC queue in the first place. This is why MIN_BUDGET is 2*kernel wcet. 

Domains have no need to block in an IPC queue. A domain just needs enough time to switch into the kernel. Once the domain is scheduled again, it's budget is replenished. If we don't care about domain overruns (since they are *not* sporadic servers, they are explicit timeslices) I think 0 makes the most sense for domain expiry, or some  number that is the amount of time it takes to get into the kernel and read the time. 0 is probably easier.   

**Now addressing the proposed solutions:**

1. Sounds good. I can't see an issue with preventing configuration of the current SC. It'll be annoying but you should be able to statically configure the initial SC anyway, and I can't think of a use case where you would want to change it dynamically.
2 & 3: we should check the assumptions on the domain on kernel entry so we know what is going to happen with commitTime. 0 should be the lower bound for domains. This might also make the fix for 1 not needed? Since we cannot be configuring an SC if our SC has triggered a timer tick.
4. Yup, assert looks wrong.

**Comment by lsf37** [comment]
Cool, thanks for clarifying the MIN_BUDGET thinking around domains, this makes sense.

Establishing at kernel entry that commitTime won't influence domain scheduling sounds right, but also like relatively high proof effort to show that this check is still correct when we reach the actual commitTime call (i.e. that we haven't tweaked anything in the state in between that is relevant). It should be possible to do, but it sounds like something to explore in more depth after this proof.

If we're right with the above, the changes for 2 & 3 will have no effect on execution, only on the proofs, and the change for 1 will make our life a bit easier for now.

I'll go ahead with preparing a patch and ping you when it's up.

**Comment by xurtis** [comment]
May be fixed when https://github.com/xurtis/seL4/issues/3 makes its way to master via #327

**Comment by MitchellBuckley** [comment]
An alternative solution is available here: https://github.com/xurtis/seL4/pull/3
I have partially verified this solution here: https://github.com/MitchellBuckley/l4v/tree/rt_DomainTimeFixes2
but a lot more work is required.

I believe that this solution is more conceptually straight-forward and quite elegant. However, the existing proofs take advantage of the fact that `preemption_point` doesn't modify state very much at all. So these changes are quite disruptive and it is quite a lot of work to fix the resulting breakages.

**Comment by kent-mcleod** [comment]
@MitchellBuckley are you referring to the call to `updateTimestamp()` in `preemptionPoint()`?

**Comment by MitchellBuckley** [comment]
> @MitchellBuckley are you referring to the call to `updateTimestamp()` in `preemptionPoint()`?

I realise now my comment was a little vague. I'm not suggesting we need to find any other way forward, I meant only to  document the state of the proofs relating to this issue. All being well, I think your solution is the right one to pursue and my comments are really only important for documentation and the time-management of the verification team (particularly under current circumstances).

On the technical side: this change means that updateTimeStamp will update both `ksDomainTime` and the extra call to `rescheduleRequired` can change the scheduler action, and the ready-queues. These extra changes to kernel state are somewhat innocent, but the existing proofs relied quite heavily on `preemptionPoint` making little-to-no change to state while this solution means that `preemptionPoint` makes some small changes to state. I think this can be easily addressed, but may require some time.
