### ISSUE TITLE
SError handling

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#260]
Currently an SError vector crashes (via `halt`) the kernel.

Given that it's possible to generate an SError from user space is this desirable? At very best it makes things very difficult to debug.

Could this be routed to the root task (perhaps?)

**Comment by bennoleslie** [comment]
As a follow up to this after thinking on it for a day. To debug this I ended up reproducing the failing code in elfloader. When an SError occurs in elfloader I get a dump of the syndrome register and the register state.

This is much better than simply receiving the 'halt' as happens in the kernel right now.

Additionally, the this `halt` is invoked directly from assembler without going through the `c_hook` or through the code which sets up the kernel entry state variables. This consequence of this is that not only does `halt` not provide useful debug information, it actively provides confusing debug information because it prints the kernel entry state variables which are not valid in this specific execution path.

**Comment by kent-mcleod** [comment]
> Given that it's possible to generate an SError from user space is this desirable?

Robust SError handing has been mostly ignored so far. There isn't an agreed design for implementing the delegation to user level as there aren't any existing kernel objects that it could be mapped to.  I believe the closest is a fault handling thread listening on an endpoint, but the kernel cannot currently deliver a system fault this way as the endpoint can only have other thread objects queued on it and the SError won't have a thread that it originates from.

> This is much better than simply receiving the 'halt' as happens in the kernel right now.

Totally! Some of the halt diagnostics need to be updated to resolve these cases where the fault isn't caused by a thread synchronous trap.

**Comment by axel-h** [comment]
seems related to https://github.com/seL4/seL4/issues/259

**Comment by Indanz** [comment]
I created a pull request to fix a similar problem, see: https://github.com/seL4/seL4/pull/369
As this issue is similar enough to our problem, I've attached it here.

We really don't want virtual machines to be able to halt the kernel, nor user space device drivers.

Routing the fault as a normal data fault is for us the easiest and most convenient solution, with minimal seL4 kernel changes.

My concern is @kent-mcleod's comment in: https://github.com/seL4/seL4/issues/346#issuecomment-818412107

> we should have a way to resolve this once we encounter an IRQ-fault scenario that isn't level triggered.

This seems like it might be such a case. Can edge-triggered SError interrupts be lost in seL4 because of the MCS_DO_IF_BUDGET check in handleVMFaultEvent()?

**Comment by kent-mcleod** [comment]
> This seems like it might be such a case. Can edge-triggered SError interrupts be lost in seL4 because of the MCS_DO_IF_BUDGET check in handleVMFaultEvent()?

Yes an edge triggered interrupt could be lost if the active thread doesn't have sufficient budget upon entry to the kernel.  In the case of #369 it may be possible for the kernel to use the new thread's fault handler to deliver the SError.  I'm not too sure how easy that would be to implement though.

**Comment by Indanz** [comment]
> Yes an edge triggered interrupt could be lost if the active thread doesn't have sufficient budget upon entry to the kernel. In the case of #369 it may be possible for the kernel to use the new thread's fault handler to deliver the SError. I'm not too sure how easy that would be to implement though.

It seems normal IRQ handling does not have this problem because the IRQ always gets handled, so it's only a problem for SError.

Missing it is still better than halting in practise, but undesired. The advantage of the current patch is that it's very minimal and doesn't add new code. It seems that's not possible and a more complex solution is required.

**Comment by kent-mcleod** [comment]
Because fault handling requires enqueuing the faulting thread on the endpoint, which under MCS requires it to have a budget.  Interrupt handling can still occur if the current thread is out of budget because a notification can be signaled by the kernel and doesn't require queuing a thread.

The SMMUv2 API has a mechanism for obtaining an asynchronous SMMU fault via receiving an IRQ and then performing an invocation to read the fault values out of the system.  This was the easiest way of handing an async error message without adding a new communication mechanism to the kernel.

**Comment by Indanz** [comment]
What guarantees that normal faults are not lost because of rescheduling? Is seL4 counting on that continuing the task on the same instruction will retrigger the same fault?

That would be good enough for device driver triggered SErrors SLVERR too. We also get dedicated IRQs for ECC errors, so we can handle those separately instead of as part of SErrors. The other SError possibilities are documented, but it's unspecified how they are actually triggered.

**Comment by kent-mcleod** [comment]
> Is seL4 counting on that continuing the task on the same instruction will retrigger the same fault?

Yes

**Comment by Indanz** [comment]
I've done the same test of writing to a read-only device register in Linux user space, and there it does not causes an SError within seL4. Our platform also has separate IRQs for ECC errors, so can be notified about those differently. Lastly, reading a write-only register does not cause an SError, but it gives a synchronous fault instead (which makes sense).

With the above in mind I've decided to go for the simplest solution of ignoring SErrors for now, see latest pull update.
