### ISSUE TITLE
Can seL4 work on hikey platform?

### ISSUE THREAD

**Issue by peakroar** [seL4/seL4#30]
Does it work at a32 mode? And which compiler fit for it? I would be very appreciate if someone could give me some detailed information.

**Comment by heshamelmatary** [comment]
Hi peakroar,

Yes, there's a hikey port and it only works in 32-bit mode. If you're running sel4test project, you can use hikey_aarch32_release_xml_defconfig file.

**Comment by domdaf** [comment]
Hello, 

I re open the issue because I'm not able to boot the sel4 image on my Hikey 620 board. I followed the steps described in the wiki [https://wiki.sel4.systems/Hardware/HiKey](url) (with some updates as some patchs are not anymore compatible with the current source files).

When I boot the image (sudo fastboot boot images/sel4test-driver-image-arm-hikey.bin -c mode=32bit)  I have in minicom terminal 
```
Synchronous Exception at 0x00000000E0000034                                     
                                                                                
Synchronous Exception at 0x00000000E0000034                                                                                                                   
                                                                                
Synchronous Exception at 0x00000000E0000034                                     
                                                                                
Synchronous Exception at 0x00000000E0000034                                     
```
Does anyone succeed to run it recently?
