### ISSUE TITLE
Kernel does not parse device tree passend on startup to get available memory

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4#373]
Follow-up from coment https://github.com/seL4/seL4/pull/365#issuecomment-842798697. OpenSBI passes a device tree, where is has carved out its memory from the available memory. Ideally, the kernel would parse this device tree at least for the available memory, then there is no need to hard-code this.

**Comment by pingerino** [comment]
Not providing device tree parsing in kernel boot is an intentional design choice. For the proofs to work we need a static layout in memory for the kernel, at least for the devices used by the kernel.

The approach we have settled on is:

- use a tool to extract the device tree on a specific device used to run seL4 then create static descriptions specifically for the kernel on that device
- pass the device tree memory region through the a dynamic user level component to parse (then you'd need to figure out how to do assurance for that). You could even use a preloader to omit certain parts of the tree or copy to desirable places in memory.

For development purposes we could add device tree parsing to debug kernels only, but it would be a *lot* of work to get this into a release kernel in any way that has assurance.

**Comment by axel-h** [comment]
I've suggested this somewhere else already, seems it would be an improvement already, when the ELF-Loader parses the DTB passed fromthe boot leoader uses this for some sanity checks when moving the images around. It could stop the loading process then and that save some debugging time figuring out what is broken there.

**Comment by lsf37** [comment]
Closing this since we don't want the feature in the kernel, and seL4/seL4_tools#108 tracks the corresponding issue for the elf loader.
