### ISSUE TITLE
Multiboot gave us no video information

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#393]
I’m not sure exactly what this means and or how to fix it. I get this from my virtual machine serial output and the simulate script

**Comment by axel-h** [comment]
When filing bug reports, please provide more details about the platform, the environment, and the executed commands.

**Comment by Ellis2781** [comment]
I see this when I run ./simulate and I am using the sel4 docker container. This message is usually the first thing to show up.

**Comment by kent-mcleod** [comment]
This is a status print statement. It's informing that there is no graphics information passed through the multiboot headers. This should be because the simulation script is passing -nographic to qemu.  If you wanted to change this, you can add `SetSimulationScriptProperty(GRAPHIC TRUE)` in a CMakeLists.txt for the project that is being built. Alternatively you can inspect the qemu command that simulate calls (`./simulate -b echo`) and remove the -nographic option

**Comment by kent-mcleod** [comment]
It's also likely that you will need additional arguments to give qemu to get it to fill in the multiboot headers.

**Comment by Ellis2781** [comment]
Oh wow I’ll try this, how would this be solved on something like a vm or real hardware?
