### ISSUE TITLE
What is the sel4 equivalent of the Unix fork() function?

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#415]

**Comment by axel-h** [comment]
There is none, because there is no such concept. You could emulate what fork() does to some extend, but this is not recommended and usually not what you really want. Instead, create a new thread and assign a vspace and other resources for communication to it. The vspace might share memory with other vspaces then depending on your needs.
Note that there are various helper libraries to manage all this (and there are even libs that emulate a fork() and other POSIX things), but I'd recommend having a look into CAmkES eventually. It allows modelling systems on a higher level and will generate all the low level code automatically.

**Comment by Ellis2781** [comment]
Axel saves the day again!
