### ISSUE TITLE
How to reboot a task?  How to delete a task?

### ISSUE THREAD

**Issue by Makebug** [seL4/seL4#448]
How to reboot a task?  How to delete a task?

**Comment by axel-h** [comment]
Please define "reboot". Also, seL4 only knows threads, but no tasks. Whoever has access to the TCB of a thread can revoke it or manipulate the cspace, vspace... Please have a look at https://docs.sel4.systems/Tutorials/threads.html and https://docs.sel4.systems/Tutorials/capabilities.html

**Comment by Indanz** [comment]
Restarting a task: Set the PC to the initial instruction/entry point and the task will "restart". However, the hard part is reinitializing all data to its initial state, but this is only necessary if the task has its own VSpace and is not sharing memory with other threads. For pure threads, the TLS data may need to be reset. Now the tricky bit: If the task has its own CSpace, you need to reset that as well. If your task can create other objects you may want to delete those too.

Delete a task: Delete all objects you created to make the task. If you allocate all resources from dedicated untyped regions, you can also revoke the UTs instead of individual objects and all objects will disappear automatically. Don't forget to cleanup your CSpace too, if necessary (if only to not leak CNode slots in your CSpace allocator). Again, if your task can create other objects you may want to delete those as well, but practically this is done by either deleting all initially "free" CNode slots when cleaning up your CSpace or those objects were allocated from the same untyped regions as the task itself.

It's best to suspend the task before doing any of the above.

How hard it is depends on your application details and what your goal is. Theoretically these things should be at most tedious, but simple enough. In practise, both operations are difficult to get right for the more complex use-cases.
