### ISSUE TITLE
Why is seL4 written in C instead of Rust?

### ISSUE THREAD

**Issue by aksum3** [seL4/seL4#487]
Hello, I find this project very interesting.  As security is the top priority, why is this microkernel written in C and not Rust?

**Comment by lsf37** [comment]
The simple answer is that the kernel was written before Rust existed, but there is also a deeper answer, which may sound counter-intuitive: Rust is a more complex language than C, so building a formal verification tool for Rust is harder, at least with the soundness guarantees that we have for the subset of C that seL4 is written in. Currently no such tools are mature enough to be usable for a code base the size and security depth of seL4.

This is because our security and correctness theorems about seL4 go *much* further than what a language type system can guarantee, even a moderately advanced one as Rust has it. In short, the guarantees that the Rust type system gives you are good, but they are not enough for what seL4 needs.

That does not mean C is generally a better language to write things in, Rust is still a more modern and safe language. If you are not doing formal verification, it'd definitely be the better choice from the security perspective. 

This situation may change with more research over the next decade. The first formal verification tools for full functional correctness for Rust programs are starting to become available, but they still have a fair way to go to achieve the same level of foundational soundness that we have here (at least if you want to take advantage of what Rust types give you).

One thing to note for formal verification of C code is that we require a restricted subset of C, to remove the corner cases and hard to understand parts of the C semantics that make the language a pain to formalise precisely. We're using the simple part of C, and staying in that subset is enforced automatically be the verification tool chain.

**Comment by gernotheiser** [comment]
There is even more to it. If you tried to write something like seL4 in Rust, you would end up with a fair proportion of the implementation being "unsafe" code, which means basically you're back with C.

C is the right tool for a high-performance microkernel. It is the wrong tool for higher-level software.

**Comment by aksum3** [comment]
@gernotheiser Would device drivers also end up with too much of the implementation being safe (and any of the other things like I/O, FS, etc.)?  I am not too familiar with this yet.

I hope to one day see an entire system including but beyond the kernel, built with the commitment the contributors here have to security, while using a modern and safe language.

I do know there are not many low-level code contributors out there relatively speaking, so it made me wonder why Rust made an entirely new language which would add a barrier to contribution.

I brought up the idea to tap into the huge TS and JS/ECMAScript ecosystem (contributors, code, funding and investment) with a subset of the former, so that more people contribute low-level code.

I was banned from the Rust forum literally without warning or reason for asking that, but how realistic is this?
