### ISSUE TITLE
sc_sporadic should imply sc_active

### ISSUE THREAD

**Issue by mktnk3** [seL4/seL4#498]
#476 bundles up the `sc_sporadic` check and `sc_active` together, to shortcut the verification process temporarily, with the understanding that `sc_sporadic` should imply `sc_active`. However, there seems to be some edge cases where this does not hold (see #496). This probably suggests potential bug somewhere. One place that `scRefillMax` is set to 0 is deletion in `finaliseCap` where we don’t modify the sporadic flag, but I am not too sure if it is actually relevant.

Apparently, adding the assert fails debug_MCS configuration, but not verification_MCS or release_MCS.

**Comment by lsf37** [comment]
The corresponding sel4test log for this failure is

```
  Running test SCHED_CONTEXT_0003 (Basic api_sc_bind/UnbindObject testing)
  <<seL4(CPU 0) [decodeSchedContext_Bind/126 T0xffffff807c23b400 "46" @43c7d0]: SchedContext_Bind: invalid cap.>>
  seL4 failed assertion 'sc == NULL || sc_active(sc)' at /github/workspace/kernel/include/kernel/sporadic.h:164 in function sc_sporadic
  halting...
  Kernel entry via Syscall, number: 1, Call
  Cap type: 22, Invocation tag: 31
```

See also [on the test itself](https://github.com/seL4/seL4/runs/3378662043#step:5:3842)

**Comment by mktnk3** [comment]
Curtis agrees that `finaliseCap` is the most likely culprit. We need to set `scSporadic` to 0 before setting `scRefillMax` to 0 here:
https://github.com/seL4/seL4/blob/master/src/object/objecttype.c#L231-L232

**Comment by kent-mcleod** [comment]
> Apparently, adding the assert fails debug_MCS configuration, but not verification_MCS or release_MCS.

asserts are only asserted in debug builds.  Release or verification builds don't compile with asserts active.

**Comment by lsf37** [comment]
What's the status of this one? The failing assertion was removed in #496, because the invariant conjectured there is currently not true.

Do we need it to be true? What happens if it is not?

Has anyone tried the proposed fix of resetting `scSporadic` in `finaliseCap`? It does seem to make sense to reset it in any case.

**Comment by lsf37** [comment]
Thanks to @michaelmcinerney for figuring out that the flag reset is indeed the only thing missing and for proving that the invariant otherwise holds. The assertion failure in https://github.com/seL4/seL4/pull/476 is additionally caused by not actually asserting the invariant (the assertion required to `scSporadic` to be true whenever `sc != NULL`, which is not the case).

#1127 should fix the problem.
