### ISSUE TITLE
(minor) Improve seL4_ARM_PageUpperDirectory_Map  documentation

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#499]
Note: This is very minor.

The description of the operations describe some error conditions, however it is also an error if the vspace has yet to be assigned to an ASID pool. This detail is described in the parameters description, but it would help the user (at least it would have helped me!) if the failure code for this case was noted in the description; other error cases are described there.

**Comment by canarysnort01** [comment]
Should there be a dedicated section on each invocation for potential error codes in the manual (and the source xml files it is generated from)?

Also, should all possible error codes and the conditions in which they are generated be documented for each invocation? Are they all considered part of the public contract?

**Comment by lsf37** [comment]
> Should there be a dedicated section on each invocation for potential error codes in the manual (and the source xml files it is generated from)?

That would be nice, yes.
 
> Also, should all possible error codes and the conditions in which they are generated be documented for each invocation? Are they all considered part of the public contract?

To me they are part of the contract. Maybe not necessarily the exact conditions under which each error reply is generated, i.e. I think there should be room for "may" in the description so that not every minor code tweak is API breaking (also some of these conditions are not easy to describe). The formal spec does describe error behaviour precisely, though.

This is a bit of a documentation project, but definitely one that would be good to have.

**Comment by canarysnort01** [comment]
> This is a bit of a documentation project, but definitely one that would be good to have.

I can give it a shot.

**Comment by lsf37** [comment]
> > This is a bit of a documentation project, but definitely one that would be good to have.
> 
> I can give it a shot.

That would be awesome!
