### ISSUE TITLE
Learning and contributing

### ISSUE THREAD

**Issue by aksum3** [seL4/seL4#504]
I have a 20-year background in high-level programming, and have always found designing secure systems interesting.  I would like to contribute, but do not have low-level programming experience.

I will learn C, but want to learn the right way instead of unlearning bad things later.  As I understand it, formal verification and a subset of the C language is key here.

Are there any books or courses on these two subjects that people here recommend?  Thank you.

**Comment by lsf37** [comment]
That is harder to answer than I thought it would be :-)

I think the main thing for low-level programming and seL4 is not so much the language, but the microkernel concepts and hardware architecture concepts they interact with. You may know these already, but if not, I would recommend the seL4 [whitepaper] as a starting point, and probably Gernot's slides and videos of the [Advanced OS course] at UNSW.

To understand the code structure of seL4, it would make sense to read through the code of seL4's Haskell/[design specification]. This will explain some things that are not idiomatic for normal C and also some otherwise perhaps strange structural conventions. You don't need to be a Haskell expert to read the code, depending on what other languages you are familiar with, it might already mage a fair amount of sense without any prior Haskell knowledge. Note that this spec written in literate Haskell style, which not all Haskell IDEs understand.

Finally, on a lower level, there is the [C subset] the verification tool chain understands, which again explains some of the non-C-like idioms used in seL4.

Given these, any "normal" source of learning C should do. seL4 code has its own memory allocator, so there is no need to go into depth about `alloc` and `free` when you are learning C, but the usual pointer data structures etc are used.

Does this answer your question or were you looking for a different direction?

[whitepaper]: https://sel4.systems/About/seL4-whitepaper.pdf
[Advanced OS course]: https://www.cse.unsw.edu.au/~cs9242/20/lectures.shtml
[design specification]: https://github.com/seL4/l4v/tree/master/spec/haskell
[C subset]: https://docs.sel4.systems/processes/style-guide.html#verification-requirements

**Comment by aksum3** [comment]
Yes, thank you.
