### ISSUE TITLE
(minor) Consolidate all DTS files in a single location

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#541]
Currently `.dts` files are scattered between `tools/dts/*.dts` and `src/plat/*/overlay-*.dts`.

I find it confusing that files are stored under `tools`, since (to me) that implies an some kind of executable function, while DTS is just data. (I realise that I could be taking *tool* way too literally).

I also find it confusing that we have them in multiple directories. Why not place the overlays next to the normal files?

In an experimental branch I placed all of these files in a top-level `dts` directory. To me this is a more logical directory layout and it's easier to find things. But I recognise that could just be me.

If there is general thought that this is beneficial I will create a PR.

If other things think it has drawbacks, I'll just close this. It isn't a big deal to me, just what I see as a minor improvement.

The big potential case against this is that it is really just churn for minor benefit, and there are other external (or potentially company internal/private) projects that rely on the current locations.

**Comment by axel-h** [comment]
i like the idea of a moving the dts files out of the tools folder, that always looked odd until one gets used to this. My understanding was these contain the Linux files and should remain unmodified. There used to be a script to update them, not sure if this is still alive somewhere.
Having the overlays in the platform folders seems a good choice to me to clearly separate things and leave details to each platform. I would not put them in the same `dts` folder, but use something like `dts/sel4` then if they have to  move.

**Comment by kent-mcleod** [comment]
Having them in tools/dts/ makes more sense to me largely because that's what I got used to.  

They were originally placed there to be next to the tools/hardware_gen.py and tools/hardware which were developed at the same time.  

Currently the tools folder is used as a folder for kernel files that don't belong in include or src or configs.  The dts files that aren't overlays are kept separate from src as they are mostly imported from external projects.  If the tools folder was renamed to something like share or var or util then having the dts folder where it is would make more sense.  I think that it's too much trouble to rename tools to something like util, but in practice that's what the tools folder has been used for.

**Comment by bennoleslie** [comment]
Thanks for the rationale. Closing.
