### ISSUE TITLE
(minor) Consolidate all CMake config files into a single location

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#542]
In a similar way to #541 I had an experimental branch where I consolidated all the `config.cmake` files into a single location. (In my case I placed them under the existing `configs` directory.

For *me* I found it easier to work with and understand the build system when it was all kept together, rather than scattered around in different places.

**Note:** This didn't require any changes to the `config.cmake` files themselves. In the cases where they reference source files they explicitly indicate the full prefix anyway.

As with #541 if people think it is a good idea I will happily make a PR. If a bad idea I'll happily close this issue.

Of course, as with #541 even if people thought this is a good idea it might be just too much churn to make it worthwhile.

**Comment by axel-h** [comment]
How much work is it to make the PR to see how this looks like practically? That might help discussing details what can change and what should stay?

**Comment by bennoleslie** [comment]
It's not too much work, but it is still some work, so I'd want at least some initial thoughts by @kent-mcleod before that.

**Comment by kent-mcleod** [comment]
It feels to me that what's better comes down to personal preference.  

Separating files into different root path hierarchies based on their type doesn't really make sense to me as you can already separate them by their file extension and name and that it's more helpful to group them in folders by subject (eg x86 or arm).  Also if you have more projects in the top level folder, do their CMake files move into the cmake folder or stay in their own project such as with libsel4.

We currently follow a convention of putting everything in the src folder unless it's some sort of interface definition in which case it goes in include (.h and .bf files).  Meanwhile the src folders contain many different filetypes (.c, .S, .cmake, .ldscript, .dts, .h.in).
libsel4/ and manual/ are different hierarchies because they're different artifacts.  There used to also be the haskell kernel implementation in here located in its own folder.  It does feel wrong to think about putting the include/ files inside src/ but I think that this is more of a separation between interface and implementation than header and source.  And so as build system is more of an implementation detail then it's fine to put it in source as it's mostly containing rules and configuration for processing source files.

**Comment by bennoleslie** [comment]
Agree regarding personal preference. Closing.
