### ISSUE TITLE
(minor) Move kernel sources / includes under 'kernel' directory

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#543]
As with #541 and #542 I had an experimental branch where I moved the kernel source and headers under a 'kernel' directory within the seL4 repo.

My motivation with doing so was to explicitly structure the code base along the lines of the two separate 'projects' that are built from the repo: seL4 kernel and libsel4.

To me it is weird having kernel src / include at the top-level and then a sub-directory with libsel4. 

A secondary motivation for me was that it made it easier to alter the build system to support a full standalone build. Thankfully, someone better at cmake than me created #410 so, this motivation goes away. As this was my main practical motivation for the change I'm less enthusiastic about it than previously.

I don't expect much support for this, but if there is I'll do the PR.

**Comment by axel-h** [comment]
I like this idea, this cleans things up. It's a bit of pain now, but good in the long run. I was waiting for you to upstream this for some time already.

**Comment by lsf37** [comment]
I don't really have a strong opinion on this. Historically, the repo used to be called `kernel`, and `libsel4` was pulled in at some later point. It does make some sense to me to separate them more clearly. Not sure if there is a specific downside.

@seL4/tsc anyone opposed to this?

**Comment by pingerino** [comment]
I'm not sure it is worth the effort, once you get used to the dir structure it's fine. 

There are *a lot* of people who are used to the existing dir structure, so this will create a headache for them, and any tooling built on top of the current layout. 

That said, I don't oppose it. But I don't think the effort:impact is worth it.

**Comment by axel-h** [comment]
An experience from our work at Hensoldt Cyber about creating an "seL4 SDK" is, that once you collect many repos together, the original repo layouts get lost. All one sees eventually is the general layout of the package - which has some odd things in there, like having the DTS file in `<kernel>/tools` and the missing separation between kernel and libsel4, so it is sometimes hard to understand why this exists actually. I would imagine anybody who aggregates things runs into such a situation sooner or later.
Now, rearranging things in custom distribution package or SDKs is doable with some work, it would be easier if the underlying repos already do this. We had long internal discussion about what view different people have on all the files and where to put things. An unfortunate lesson also is, that once engineers really start digging to the details and customize things, they find the original repos and note their tweaking does not match there. They tend to dislike the rearranging because that makes hacking, cherry-picking and upstreaming harder - but forget how nice they layout was when they started on all this.
Another risk with the current layout I see is, that is allows scripts/includes to make some dangerous assumptions where to find things by just doing some relative moves instead of using proper paths. Many of these quirks have been cleaned up already, but it still something to watch out for constantly.
The "seL4 core" movement and the PR from @kent-mcleod  that allows creating a kernel installation package has opened a nice option now to do things differently.  But I still think the move into separate folder has a benefit the long term, even if the actual work looks cosmetic and likely brings some potential pain that things have to change. The catch is, that currently I's assume users can still handle this. The more the ecosystem grows, the harder such changes will get.

**Comment by bennoleslie** [comment]
> I'm not sure it is worth the effort, once you get used to the dir structure it's fine.
> 
> There are _a lot_ of people who are used to the existing dir structure, so this will create a headache for them, and any tooling built on top of the current layout.
> 
> That said, I don't oppose it. But I don't think the effort:impact is worth it.

I don't disagree. Having an explicit disagree / rejection is as good to me as others agreeing.

On balance I still have a weak preference for rearranging personally, but without strong, unanimous support it's not something I'm going to spend time advocating for. I'm going to close this as I originally opened it, but if @axel-h wants to re-open and continue trying to convince others I'm happy for that too.

**Comment by kent-mcleod** [comment]
I like that the kernel paths are shorter by default as it's the main part of this repository.  Having to type an extra directory in front of every kernel path name adds more friction when interacting with the files for source control or using them in text editors.  Having every file be at the end of a long path name can get quite annoying when trying to distinguish them in pull requests or click through repository browsers.  `src/api/syscall.c` is more concise than `kernel/src/api/syscall.c`.  

Even if I thought that having an extra directory at the top was better, I still agree with @pingerino.  Because this isn't an internal private repository, you can't easily estimate the total amount of pain that renaming 80% of the files in the repository would create for everyone that's using it.  For @axel-h, you could still use something like git-subtree to stitch together your own repository layout and have people's cherry-picked commits still be able to be applied upstream too.

**Comment by bennoleslie** [comment]
My last comment I promise :).  I agree with everything @kent-mcleod has said, *but* I think it's unfortunate that we have this kind of 'unintended' external coupling beyond the boundaries of the project. I may have limited exposure to other system setups, but it's surprising to me to have external project depend on the source code layout of a project, and not just the build artefacts.

(Note: I also realise this isn't the only thing Kent it talking about when he says *everyone that's using it*. I also have various private branches and unnecessary churn makes that difficult). 

I'm not saying this change is good, and cost:benefit should always be considered. I just worry that any change can always be blocked by "another project depends on the source code layout".

**Comment by kent-mcleod** [comment]
There have been 8300 unique clones of the repository in the last 14 days.  Our primary distribution method of this project is via the source code, not by binary distribution.

- How many times has someone written down a URL to a particular line number in the project in an issue tracker or email?
- How often do people click through the history of the code base following how a particular function evolved over time?
- How often do people `git blame` something to figure out who to ask about a particular implementation detail?
- How many times in documentation or blog posts has some piece of source code been referenced via a raw path?

I'm going to call all of these things "soft" dependencies.  

"hard" dependencies are then things like:
- #including a file from the kernel repository in another project (#include <sel4/sel4.h>)
- Using the `gcc.cmake` toolchain file, to initialize the build of another project
- Using the kernel.dtb file as an input to a userlevel build tool
- Using the kernel.elf when creating a bootable image
- Depending on a kernel's CMakeCache.txt setting from another CMake project like sel4test

"hard" dependencies are what I consider @bennoleslie is referring to, and I agree that having unintended external coupling here is bad.  Moving libsel4 header files around shouldn't break anything wanting to include the libsel4 library and this is what an indirection like an install step tries to achieve.  There are cases where we have external coupling of hard dependencies that we should have avoided (like CMake Cache variables shared across artifact boundaries).  But even if we did manage to avoid all bad "hard" dependency external coupling, there would still be the "soft" coupling that comes from having an open source project. Making changes that break "soft" coupling is unavoidable when you need to make changes, but this doesn't mean that we should just pretend that the only dependencies are "hard" dependencies when evaluating impact of a change.

**Comment by axel-h** [comment]
There is a source code dependency for every branch, fork and pull request - but that is the general life with open source projects. Aside from this, it seems to me there are still 2 views on the sel4 project. One is the quite kernel centered view, the other is the userland/ecosystem view (there might be hypervisor/VMM view in between also). The first one is strongly tied to the kernel's sources and may have some academic work attached where people fear loosing time to chase such changes. The other userland view does not really care and should just use a "sel4 package" to develop a rich userland. As long as the includes are set up properly, nothing actually changes here if the kernel sources are restructured. 
The great unknown is, how many of the project out there really depend this deep on kernel source details. My impression here is, that the actual problem might be, that various project use arbitrary kernel version, some not even based on releases and some have branched off at some point into whatever they do. Updating the kernel then becomes a pain anyway due to too much tie-ins or not publishing changes that allow aligning things better with the master branch. My opinion is, that for actively maintained branches only few changes really leave a terrible state, the rest can be migrated over with the time (say 3-6 months). For branches not maintained or diverging for months/years, there is a problem anyway, but even cherry-picking changes from master is not trivial there. And if the proofs still cover them might be questionable also.

What would be the known project that will cry out loud here
- the AOS course?
- any pending MCS work?
- any serious porting work?
- any research work?
- any hypervisor work?
- the device driver framework?
- .... company branches, maybe with long term commitments?

I wonder, do we have a process to reach out to the wider community how they feel about this? Should this become an RFC to just collect the wider feedback here and especially collect point that are real blockers?

**Comment by bennoleslie** [comment]
> Making changes that break "soft" coupling is unavoidable when you need to make changes, but this doesn't mean that we should just pretend that the only dependencies are "hard" dependencies when evaluating impact of a change.

I like your way of separating into "soft" and "hard". And I mostly agree with what you write here. (I did close the issue after all!). I mostly just want there to be recognition that it is a trade-off and not a binary here. we shouldn't slow down evolution *just* because there are some soft coupling, equally we shouldn't make change without considering them either. It's definitely impossible to enforce, but I think to the extent possible most of the soft uses referenced above *should* refer to a particular version/commit. (Of course, they don't! That's the tradeoff!). I feel git does a pretty good job of handling moves when it comes to merges and moves. (At least if you mostly do a move and a change in separate commits). 

We should all certainly consider these soft tradeoffs with any change. Any I still feel like I'm weakly in favour despite these soft dependencies. But as I already mentioned, it is so weak on that opinion that I'm more than happy to defer to other who evaluate the tradeoff in the other direction.

I guess I come from a place of fear the inertia of minor painful changes now over the potential for changes to build up to the point of needing a big-bang later. (I've gone through python2 to python3 which I attribute in part to a resistance to painful minor evolution when needed with a consequence of a much more painful big bang change later).
