### ISSUE TITLE
(minor) Move {llvm,gcc}.cmake from top-level directory

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#547]
In an experimental branch I moved `llvm.cmake` and `gcc.cmake` from the root directory into the `tools` directory.

I'm not sure `tools` is really the right place. But I really don't think that the root directory is either. 

Having them in the root makes them seem a lot more important and special than they actually are. (Although they are a little bit special, there is definitely some magic going on with them compared to other `.cmake` files).

Either way, I don't think they should clutter up the root.

But, like some of my other recent minor enhancement suggestions this could be noisy, unnecessary churn. If there is agreement I'll do the (trivial) PR to make it happen.

**Comment by axel-h** [comment]
I like the idea.

**Comment by kent-mcleod** [comment]
> Having them in the root makes them seem a lot more important and special than they actually are. (Although they are a little bit special, there is definitely some magic going on with them compared to other `.cmake` files).

When they were originally added they needed to be explicitly passed to an initial cmake configuration via -DCMAKE_TOOLCHAIN_FILE and many instructions and scripts depend on knowing where those files are (https://github.com/seL4/seL4_tools/blob/master/cmake-tool/init-build.sh#L45).  This is no longer the case, but the functionality still works for any scripts that still depend on it.

Moving these files would also require any existing build folder that uses one of them to be deleted and recreated in order to avoid weird effects that could happen from CMake's behavior of caching the toolchain file location internally in the build state.  Since https://github.com/seL4/seL4/blob/master/configs/seL4Config.cmake#L249 was added, there would probably at least be a cmake error generated, but it would still be pretty inconvenient.

In my opinion it's not worth it even though it frustrates me that the main directory is getting cluttered.  Maybe we could consider removing files like gdb-macros which as far as I'm aware haven't been used in over 7 years (https://github.com/seL4/seL4/commits/master/gdb-macros)

**Comment by bennoleslie** [comment]
If `gdb-macros` is unused I agree on getting rid of it.

Thanks for the context on other projects importing this. Agree not worth changing if that occurs.

I think that is part of why I'd like something like 'seL4 core' an why I like the efforts in #410 . I think things like random cmake files are an internal detail. Having other projects, either internal to seL4 foundation, or external, relying on details of the kernel build system feels like unnecessary coupling to me. To me it seems like you should be able to modify how the internal structure of the kernel repo, and if it builds the same binaries it shouldn't impact external repos. But that isn't an argument to be prosecuted in this issue. Closing.
