### ISSUE TITLE
Inconsistent method naming in manual

### ISSUE THREAD

**Issue by bennoleslie** [seL4/seL4#565]
In the method name of the document in some cases phrases are used (with spaces and capital letters) and in other places camel-case is used.

For example, we have "Asid Pool Assign" by "AssignVSpace".

It's not clear what is 'right'. I don't have a strong opinion, but I'd lean towards camel case (no spaces).

**Comment by axel-h** [comment]
Using the method name would allow cross referencing this everywhere. Even in a paragraph with verbose explanations mentioning the function name might make sense.
Other opinions?

**Comment by lsf37** [comment]
I was going to say, the xml should define the name and the rest of the manual should use that, but the multiple names are already present there:

```xml
<method id="TCBSetSchedParams" name="SetSchedParams" manual_name="Set Sched Params" manual_label="tcb_setschedparams" >
```

`id` is internal and probably necessary, but I'd agree that unifying `name` and `manual_name` would be an improvement and that `name` (i.e. camelCase) is better because it makes it clear that it is a technical reference instead of prose.

It might even be possible to find and link these automatically in the text (although the presence of `id` indicates that there are probably name overlaps, so maybe not).

**Comment by bbrcknl** [comment]
@lsf37 @Indanz
Just to be clear, should the `name` and `manual_name` be the same, and in camelCase, e.g.

````
<method id="TCBSetSchedParams" name="setSchedParams" manual_name="setSchedParams" manual_label="tcb_setschedparams" >
````

**Comment by Indanz** [comment]
> @lsf37 @Indanz Just to be clear, should the `name` and `manual_name` be the same, and in camelCase, e.g.

If you look at the user of these variables, then making them the same makes no sense, as `manual_name` will by default be `name`, so it only makes sense to specify `manual_name` if it's different than `name`:

https://github.com/seL4/seL4/blob/b59fa0ed20b444aa52b346e5d94c7669ceaca5b1/libsel4/tools/syscall_stub_gen.py#L857

`id` must match the invocation enum value, so has to match the C source code.

`name` is used to name return structures and stubs, so shouldn't be changed either.

`manual_name` is used for the API comments and the manual's chapter names. All the words are capitalised with spaces between because that's how chapter titles are written in English.

Another use seems to mark system calls as MCS versions, if there is a non-MCS one that has a different API like "Set Sched Params (MCS)".

All-in-all my impression is that the current `manual_name` isn't as inconsistent as it may seem, the differences are there for a reason, to make things clearer (just like e.g. "Non-Blocking Send" for seL4_NBSend). The main thing is that all `manual_names` that are the same as `name` should be removed. For the others, go through the manual's table of content and see what looks best there and use that.
