### ISSUE TITLE
Thread code nitpick

### ISSUE THREAD

**Issue by berkus** [seL4/seL4#57]
```
src/kernel/thread.c:125:13: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
    if ((!!(!seL4_Fault_get_seL4_FaultType(sender->tcbFault) != seL4_Fault_NullFault))) {
```

I think there's a mess with `!` usage here.

**Comment by AdrianDanis** [comment]
This code most have gone through some semi automated refactors. It is actually correct, although I can understand a compiler wanting to give a warning. Since `seL4_Fault_NullFault` is `0` then `!seL4_Fault_get_seL4_FaultType(sender->tcbFault) != seL4_Fault_NullFault` is equivalent to `seL4_Fault_get_seL4_FaultType(sender->tcbFault) == seL4_Fault_NullFault`. We should just change to the latter though, as it's far more readable.

**Comment by berkus** [comment]
Thanks for clearing this up, I think i've seen one more place like this - i will post here when i find it again.
