### ISSUE TITLE
Where is the kernel init function on x86?

### ISSUE THREAD

**Issue by Ellis2781** [seL4/seL4#667]
I find the init_kernel() in boot.h on the arm and riscv platforms however, I can’t seem to find the same on x86. Where is this function? Does it have a different name?

**Comment by kent-mcleod** [comment]
On x86 the first C function called is `boot_sys()`.  Different architectures have different boot implementations because most boot functionality is arch specific.  Every kernel configuration currently has a `head.S` file that declares `_start` as the point where the kernel expects control-flow to start (for at least the primary CPU node). `head.S` is either located in `src/arch/$arch` or `src/arch/$arch/$mode` depending on the selected architecture and mode.
