### ISSUE TITLE
i want to create a simple system program for sel4 using python, although i have read almost all the documentation but i couldnt find a way to do so. 

### ISSUE THREAD

**Issue by maimuna99** [seL4/seL4#669]

**Comment by axel-h** [comment]
I'm not aware that a python runtime port for seL4 exists that would allow running python applications. It would make an interesting project to have python running. Starting with MicroPython (https://docs.micropython.org/en/latest/develop/porting.html) might be an option. Once this is running you'd have think about loader (UART, Network, SD-Card....) for custom python applications.

**Comment by lsf37** [comment]
I might be misremembering, because I can't find the code for it, but I believe there was a student project many years ago that had a prototype of this working on an old version of seL4. That code would not work any more even if I could find it, but it does indicate that it should be fairly possible port the language runtime.

In any case, it would be a new project and it is not something that is currently supported. If someone wants to do it, that'd be cool, though. It is sort-of mentioned towards the bottom of the suggested projects page at https://docs.sel4.systems/SuggestedProjects.html

**Comment by maimuna99** [comment]
can i have a look on the student project you mentioned earlier even if the code is not working any more , that would be really helpful and which version he was working on.

**Comment by lsf37** [comment]
Sorry, like I said, I can't find the code -- otherwise I would be very happy to provide it. (It was not my student, but supervised by someone else in the group many years ago). 

Maybe @ikuz remembers something about that one?

**Comment by wom-bat** [comment]
The new LionsOS code has a micropython interpreter in it.
