### ISSUE TITLE
RFE: Prove that a vCPU is a refinement of the physical CPU

### ISSUE THREAD

**Issue by DemiMarie** [seL4/seL4#671]
This is admittedly a longshot, but it would be nice to prove that the vCPU is a refinement of the physical CPU.  This requires formally verified instruction emulation (on x86), along with verified nested virtualization and nested IOMMU support.

I believe this falls in the category of “doable, but a lot of work and would likely take a lot of funding”.  Feel free to close this if it isn’t practical.

**Comment by lsf37** [comment]
seL4 does not actually aim to guarantee this, and API-wise it is fully observable that a vCPU is not a CPU. That is intended.

It's the job of a user-level virtual-machine manager to actually emulate the CPU to a degree that is useful to the guest OS, but even that is often not a 100% emulation (although it maybe could be). It is common for guest OSes to be aware that they are running in a VM and to have specific drivers to communicate with other VMs etc that make use of that fact.

So, in conclusion, this is not something we can prove, because it not true on the seL4 level, and even usually not true on the VMM level.

Even if it was made to be true on a VMM that really does fully emulate everything (including cycle counters etc), I doubt that it would be feasible to verify on Intel. Possibly on older Arm or on more recent RISC-V architectures, because they are simpler. This might sound counter-intuitive, but I would estimate this to be a *much* bigger job than OS verification, because this would have to model all aspects of the hardware, whereas we can abstract from hardware instructions and mechanisms that we do not use and only describe what their maximum effect is on the machine state. For instance, there are many user-level instructions the kernel does not use, and the only thing it has to know about them is that they can change only registers and memory the user has access to, which means there is nothing much to prove about them. That would be a very different situation then.

**Comment by DemiMarie** [comment]
@lsf37 That makes sense.  Perhaps a better idea would be “prove seL4 in a VM under seL4 works correctly, assuming a correct userspace VMM”.  Nevertheless, even this is a longshot, especially on x86_64 where *every instruction that accesses MMIO memory* might need to be emulated.  Xen has an emulator that is 12,000 lines of C code.

What *would* be useful is a way for a VM to operate directly on seL4 kernel objects by means of hypercalls, without having to round-trip through userspace.  Of course, this would not be allowed unless the VMM granted it that ability.  I am also not sure if nested virtualization can be reasonably performant without kernel support, but that is a different issue.
