### ISSUE TITLE
Setup documentation is hard to read.

### ISSUE THREAD

**Issue by Shadowblitz16** [seL4/seL4#696]
Please separate documentation on how to setup seL4.
Ideally there would be a separate page for window, mac, linux and for docker, repo.
And a main page pointing to them.

something like...
```
- docker
    - windows
    - mac
    - linux
        - ubuntu
        - debain 
- repo
    - windows
    - mac
    - linux
        - ubuntu
        - debain 
```

**Comment by axel-h** [comment]
I think Windows is not supported actively at the moment, but at least one student recently got it working eventually using WSL somehow. For Mac I'm not sure how actively this is supported. That leave Linux/Ubuntu, where 18.04 is still the baseline the documentation builds on.
With seL4 being an open source project, contribution to the documentation are always welcome. It is hosted at https://github.com/seL4/docs and https://github.com/seL4/website and taking PRs. That would be the fastest way to improve things based on you personal experience. Otherwise it can take some time until somebody finds the time to wrap things up that have been reported as issues - and the discussion on the issues has to serve as interim solution. However, given the current situation, an extra test cycle in the next release with a plain 20.04 Ubuntu system might be worth considering besides just a code freeze and extended CI tests passing. This might be subject to available resources, though.

**Comment by lsf37** [comment]
There is no plan to support Windows or Mac.

Ubuntu 20.04 is the plan to support soon (together with the new Debian stable), but clang-11 still needs a bit of work.
