### ISSUE TITLE
question about file kernel/include/arch/riscv/arch/64/mode/hardware.h

### ISSUE THREAD

**Issue by chenyangyy** [seL4/seL4#823]
I notice that the PSpace is 254G, it will not be able to map the whole physical address space, so how can we use the "not kernel addressable" block in the top of the physical address space? Which segment of the physical address space should be mapped into the "PSpace"?

**Comment by GooTal** [comment]
Thank you! We are from the same team trying to port seL4 to loongarch.

The physical memory layout of our platform :
![image](https://user-images.githubusercontent.com/40800103/161191413-207ae355-25ae-4e8d-a29d-0082232d7615.png)
It is true that 256MB of memory is in the low address and another bigger area is in the high address. And our physical address space is 2^48.

In this file `kernel/include/arch/riscv/arch/64/mode/hardware.h`, `PSpace` area is mapped in a memory region in physical address space, and `KERNEL ELF` is at `KERNEL_ELF_PADDR_BASE`. 

In our platform, in which part of physical memory should we map PSpace? Do we need to adjust the size of PSpace?

Is this mapping solution possible? ( `PADDR_BASE` = 0, `KERNEL_ELF_PADDR_BASE` = 0x9000_0000, `PADDR_TOP = PPTR_TOP - PPTR_BASE` ) , and the `PADDR_TOP` may be adjusted due to the size of PSpace?

**Comment by GooTal** [comment]
@axel-h 
Thank you! @chenyang1016 and I are trying to port seL4 to loongarch. And we would be much appreciated if you could give us more help.

The physical memory layout of our platform :
![image](https://user-images.githubusercontent.com/40800103/161202871-39af2034-9f0f-483a-9cf4-1db9e02e8ad0.png)
This figure is from section 3 of this HTML doc: https://loongson.github.io/LoongArch-Documentation/Loongson-7A1000-usermanual-EN.html#address-space

The memory low address space is for DMA of some old devices,  which coincides with 0x8000_0000~0x8fff_ffff ( We notice that spike memory just starts from 0x8000_0000 and doesn`t save space for old devices DMA? ). The figure below is the printed information simulating loongarch machine with qemu. Besides, our physical address space is 2^48.
![image](https://user-images.githubusercontent.com/40800103/161191413-207ae355-25ae-4e8d-a29d-0082232d7615.png)

In this file `kernel/include/arch/riscv/arch/64/mode/hardware.h`, `PSpace` area is mapped in a memory region of physical address space, and `KERNEL ELF` starts from `KERNEL_ELF_PADDR_BASE`. 

Here are our questions:
* In our platform, in which part of physical memory should we map PSpace? 
* Do we need to adjust **the size of PSpace**?
* How to set the **OFFSET** value described below?

Is this mapping solution possible?
 ( PADDR_BASE = 0, KERNEL_ELF_PADDR_BASE = 0x8000_0000+ **OFFSET** , PADDR_TOP = PPTR_TOP - PPTR_BASE ) . The PADDR_TOP may be adjusted due to **the size of PSpace**. KERNEL_ELF_PADDR_BASE starts from 0x8000_0000 + **OFFSET** , so we also want to know how to set **OFFSET** value. (it`s 0x400_0000 on spike, 0 on arm and 0x10_0000 on x86_64).

**Comment by axel-h** [comment]
Do I understand you right that the "low address space" range `0x0 - 0x0FFF_FFFF` is just an alias of the range `0x8000_0000 - 0x8FFF_FFFF`. In this case, I'd say there is no need to care about the low memory area at all. Just use the memory from 0x8000_0000 on. A driver for an old DMA peripheral just needs to do the translation then. Things might get tricky when an IOMMU in involved that the seL4 kernel controls, but even this might be managable.
Also, thinking practically, how many "old DMA peripherals" are there actually that we have to care about?

**Comment by axel-h** [comment]
`OFFSET` is `0x0400_0000` on `spike` (RISC-V actually), because OpenSBI uses the first 2 MiB or RAM 0x8000_0000 - 0x8020_0000. Another 2 MiB are then reserved for the ElfLoader image, so it can "unpack" the kernel to 0x8400_0000 and copy the user image(s) afterwards. There is some work in progress to relax this a bit more and make thing like on ARM.
On ARM (64 bit) , no such reservation exists. The TrustZone stuff is somewhere else, often at the end of the physical memory.
I'm not an x86_64 expect, so I cannot comment on this.

On 64-bit systems I'd recommend to start with `PADDR_BASE = 0`and `OFFSET = 0`. Set a memory region in the device tree that starts at `0x8000_0000`. From the memory layout above, I don't see a reason why that should not work. There seems no physical memory at very high addresses towards the end of the 64-bit space, so there is no need to be have to cover this?

**Comment by GooTal** [comment]
Thank you. @axel-h 
I still want to know how to set the size of Pspace window, which is 254GiB on riscv. Is this there something particular that we need to care about? Or just let the Pspace big enough to cover the area of kernel elf?

I notice that on Linux systems, virtual kernel address space can be mapped to the whole physical space. 
But on seL4-riscv, the Pspace of the kernel is mapped to a certain region(254GiB size) of physical address. And I notice that some space is not kernel addressable? Is it due to the difference between the macro kernel and microkernel?

**Comment by axel-h** [comment]
The size of PSpace just has to be big enough, so you are free to chose a value. The actual value may depend on how the MMU works and how much physical address space is supposed (usually less than 64 bit).
I'm not familiar how things are on Loonson. Does it also split the virtual memory in a lower part (commonly used for user space) and an upper part (commonly used for kernel space)? Can both sized are chosen independently or do they have to be the same?
The RISC-V size is basically driven by using the maximum possible (256 GiB) and reserving 1 GiB for the Kernel ELF and 1 GiB for device mapping. These sizes come from the area an MMU table entry can cover. It's quite similar on ARM (64-bit), but page tables usage in the kernel is a bit more fine grained.

**Comment by axel-h** [comment]
> I notice that on Linux systems, virtual kernel address space can be mapped to the whole physical space. But on seL4-riscv, the Pspace of the kernel is mapped to a certain region(254GiB size) of physical address. And I notice that some space is not kernel addressable? Is it due to the difference between the macro kernel and microkernel?

Well, seL4 works different than Linux. And seL4 uses the permanently mapped kernel window as a way to access physical memory using just a simple address translation. This add some limitation (especially on 32-bit) on what can be accessed. I'm not sure how Linux does it internally, it may use some lazy- on-demand mapping and thus is more flexible. It's not really a micro kernel limitation, just different concepts that different operating systems uses.
