### ISSUE TITLE
tmp/ccuAaHAM.s

### ISSUE THREAD

**Issue by Leoncoci** [seL4/seL4#837]
When I was in debug, I found a lot of instruction errors in the tmp/ccuAaHAM.s file, I want to know why and how this file is generated, thank you for replying :)
![image](https://user-images.githubusercontent.com/45042260/166180858-737a3252-632b-4ce9-b8d9-92fd6135605c.png)

**Comment by axel-h** [comment]
That look like a intermediate file generated by the toolchain. Since `loonarch64` is a new architecture, either something is broken there or you are pulling in an assembly file copied from ARM/RISC-V that needs to be translated. From the screenshot it's hard to guess what is really failing there, but making the compiler save the intermediate files allows looking into them - that might give a clue.

**Comment by Leoncoci** [comment]
Thank you for your reply. I guess the result of his compilation was the final kernel, and I completed the modifications by keeping this intermediate file, thank you very much
