### ISSUE TITLE
include/arch/riscv/arch/64/mode/hardware.h

### ISSUE THREAD

**Issue by chenyangyy** [seL4/seL4#840]
kernel can be addressed through the PSpace，so why do we still need Kernel ELF above PSpace？It looks like that they are both mapped to the same physical memory area where the kernel actually resides.

**Comment by kent-mcleod** [comment]
Sometimes it's because smaller addresses can be used at the top of the address space such as for x86_64. Longer term it's because a new API called KernelImageClone allows different copies of the kernel image in different regions of physical memory but same virtual address to minimize cache timing channels.

**Comment by chenyangyy** [comment]
So is the region "Kernel Devices" for the same reason?

**Comment by kent-mcleod** [comment]
KernelDevices came about because on some architectures, the kernel window isn't large enough to cover all physical address space (eg arm32). This meant that an extra region was needed for device MMIO mappings that were outside of the kernel window map.  EG the imx6 sabre platform has a kernel window mapping starting at a physical address: 0x10000000 and the interrupt controller starts at physical address 0xa01000 which is outside of the kernel window mapping. 
So the Ram memory is mapped from [0x10000000, 0x2ff00000) into virtual range [0xe0000000,0xfff00000) and the interrupt controller is mapped into a 4k page slot between [0xfff00000, 0xffffffff).

**Comment by axel-h** [comment]
Even if the kernel windows is big enough, I was assuming this is just for accessing things as "ordinary memory" (accesses are cached, re-orderable ...). Mapping devices requires different settings to ensure the accesses are really happen exactly as stated in the program code. This is highly architecture specific in the end, but the kernel device area provides the necessary flexibility to allow such mappings.
