### ISSUE TITLE
Question about kernel_stack_alloc and sp register in kernel/src/arch/riscv/traps

### ISSUE THREAD

**Issue by GooTal** [seL4/seL4#853]
I notice that in the file `kernel/src/arch/riscv/traps.S`, if **smp is not enabled**, sp register value will be stored here:
```
#ifndef ENABLE_SMP_SUPPORT
  STORE sp, (1*REGBYTES)(t0)
#endif
```
Then sp is assigned to ` (kernel_stack_alloc + BIT(CONFIG_KERNEL_STACK_BITS))`
```
  /* Load kernel's stack address */
  la sp, (kernel_stack_alloc + BIT(CONFIG_KERNEL_STACK_BITS))
``` 
Why sp is assigned to ` (kernel_stack_alloc + BIT(CONFIG_KERNEL_STACK_BITS))`?

The `kernel_stack_alloc` in the figure below, defined the stack for each kernel. Do all of the running tasks on one core use the same stack? If so, when sp is assigned to ` (kernel_stack_alloc + BIT(CONFIG_KERNEL_STACK_BITS))`, will the current thread\`s trap handler override another thread\`s data? I notice that sp is restored to the previous value in the function restore_user_context, so sp (the value of ` (kernel_stack_alloc + BIT(CONFIG_KERNEL_STACK_BITS))`) is not used?
![image](https://user-images.githubusercontent.com/40800103/169645114-db6bcf7c-4eeb-4f62-be3e-6c8f124baf76.png)

![image](https://user-images.githubusercontent.com/40800103/169645553-78ddd1be-a32b-4a1f-b24f-b90e9035f5f7.png)

Thanks for your time!

**Comment by axel-h** [comment]
I'm not sure I fully understand your question, so the answer will be a bit more verbose:
The kernel has its own stack, it is not shared with any user thread. A userland trap handler for one thread is basically just another userland thread that receives a message about the trap. The kernel uses it's own stack when it is running, e,g, during syscalls, interrupts or as "root" trap handler that sends the trap message then to a userland thread that is the designated trap handler). 
In SMP configurations, each core runs a separate kernel instance. Each instance uses a different stack, because each kernel per core is largely independent. A big kernel lock is obtained at places where global state data is modified and concurrency is not allowed. 
Nowadays, on most architectures (and I'd assume this holds for Loongson also?) the stack grows downwards (to lower addresses). Thus, the stack pointer is initialized to point to the end of the stack. 
What you see there is the change from user to kernel on kernel entry and later the user stack restoration on kernel exit. On kernel exit a different thread might be restored than the one that was active on kernel entry.
The code for stack setup can be different on SMP and non-SMP configurations due to historic reasons. That can be a bit confusing and the whole code could get some cleanup/unification one day.

**Comment by GooTal** [comment]
Oh, thank you. I\`ve learned a lot from this work by discussing and coding.
I still got a question (Sorry for my poor knowledge). In the file traps.S, sp is assigned to `(kernel_stack_alloc + BIT(CONFIG_KERNEL_STACK_BITS))`, which is the end of the stack. How can we make sure that the stack for this kernel is empty?

**Comment by axel-h** [comment]
There is no need for the stack to be empty - what would be "empty" actually, filled with zeros? Any contents there will be overwritten anyway when the stack gets used.

**Comment by GooTal** [comment]
> There is no need for the stack to be empty - what would be "empty" actually, filled with zeros? Any contents there will be overwritten anyway when the stack gets used.

You mentioned the contents may get overwritten. Will it cause any trouble if we overwrite these previous contents?

Maybe some functions already used these contents and it\`s ok to override them?

Thanks for your time.

**Comment by axel-h** [comment]
Assuming the kernel's memory management is sane, nobody else will use this. The buffer used for the kernel stack(s) is part of the memory reserved by the kernel.

**Comment by GooTal** [comment]
Ok, much thanks!
