### ISSUE TITLE
Is CDT a global tree in kernel or per thread tree in kernel?

### ISSUE THREAD

**Issue by FinnZhang** [seL4/seL4#855]
There are some words below in the seL4 manual.
> that seL4 maintains a capability derivation tree (CDT) in which it tracks the relationship between these copied capabilities and the originals

As the words says, **seL4** maintains a CDT.  That means there is only one global CDT in the seL4 kernel. But I can't find any global CDT exist or maybe I misunderstand meaning of CDT.
Someone says CDT is a tree at per thread level but I disagree. So I am so confused about the CDT without more document.
Could you please answer my question or give me more references about CDT? Thanks a lot.

**Comment by Indanz** [comment]
From how I understand it, it's a single, global tree, with the root server's TCB having the root node of this tree as its associated CSpace,

**Comment by FinnZhang** [comment]
> From how I understand it, it's a single, global tree, with the root server's TCB having the root node of this tree as its associated CSpace,

Thanks for your reply. Would you mind providing me some references about CDT data structure principle ?

**Comment by Indanz** [comment]
I've got my information from the [seL4 manual](https://sel4.systems/Info/Docs/seL4-manual-latest.pdf), see figure 3.1. But it helps to actually use seL4 to write programs, because then you encounter all the details and you get an overall view of how it all ties together. The CDT is about object creation and lifetime.

Keep in mind that seL4 delegates _all_ memory management to user space (with the only exception being the startup task), so there is nothing else than what is described in the manual. Every object reference you have to configure yourself, so you know exactly how everything ties together.

Although the capability derivation tree is a tree structure, all CSpaces together are one big graphs and not necessarily a tree. The starting node (or "root") of that graph is defined per TCB as its associated CSpace. How far each task can traverse the graph is defined by the graph's structure and the CNodes' guard sizes.

Conceptually the CDT is managed as a subtree of the global CSpace graph.

This is introduces limitations that are not always documented, like you're not allowed to put a cap to an untyped region into a CNode derived from that untyped region.

**Comment by FinnZhang** [comment]
> I've got my information from the [seL4 manual](https://sel4.systems/Info/Docs/seL4-manual-latest.pdf), see figure 3.1. But it helps to actually use seL4 to write programs, because then you encounter all the details and you get an overall view of how it all ties together. The CDT is about object creation and lifetime.
> 
> Keep in mind that seL4 delegates _all_ memory management to user space (with the only exception being the startup task), so there is nothing else than what is described in the manual. Every object reference you have to configure yourself, so you know exactly how everything ties together.
> 
> Although the capability derivation tree is a tree structure, all CSpaces together are one big graphs and not necessarily a tree. The starting node (or "root") of that graph is defined per TCB as its associated CSpace. How far each task can traverse the graph is defined by the graph's structure and the CNodes' guard sizes.
> 
> Conceptually the CDT is managed as a subtree of the global CSpace graph.
> 
> This is introduces limitations that are not always documented, like you're not allowed to put a cap to an untyped region into a CNode derived from that untyped region.

Thank you very much. I will read the source code for more comprehensive knowledge about that.

**Comment by kent-mcleod** [comment]
> This is introduces limitations that are not always documented, like you're not allowed to put a cap to an untyped region into a CNode derived from that untyped region.

I believe that you can do this. You aren't able to copy an untyped cap if it already has any children, but you can use `seL4_CNode_Move` to move an untyped cap. seL4_CNode_Move doesn't have any restrictions apart from the src slot is valid, contains a non-null cap and the dest slot is empty. 

> Thank you very much. I will read the source code for more comprehensive knowledge about that.

There's also a cspace tutorial: https://docs.sel4.systems/Tutorials/capabilities.html

**Comment by Indanz** [comment]
> Thank you very much. I will read the source code for more comprehensive knowledge about that.

Yes, that's really the best way to get detailed information.

> I believe that you can do this. You aren't able to copy an untyped cap if it already has any children

You're right that a move is possible, so what I said was wrong. The limitation is only for copying. I assumed it had something to do with the CDT, but it's unrelated.

If the CNode is derived from the untyped cap then that's a child, so a copy is not possible.

I find it irksome that I have to first make a copy of the untyped cap, do all allocations from that, and then move that cap to it's final place. Logically the end result is the same, but reached more convoluted. Why not allow non-empty copies which mark the src full and copy the src capFreeIndex value to dst?

**Comment by lsf37** [comment]
> * Copying doesn't require you to specify the size of the new untyped cap. You just get the whole thing.

This is why `copy` has restrictions -- there can only be one active allocator for each memory region. When you retype an Untyped, you get authority to a sub-region and the original Untyped can no longer allocate in that region (because the free-index pointer moves). Both can `free` in that region, but if the parent `free`s, the child Untyped disappears, so there is no inconsistency. If you were to just copy it on the other hand, you'd have two Untypeds that think they have authority to allocate in the same memory. This wouldn't lead to problems straight away, but once you have that situation, you can delete in one, and then allocate in the other, and after that allocate the same memory twice, or try to delete twice etc. You'd need to adjust quite a bit of the logic to make sure all of these situations are handled correctly, and I don't think you'd get more degrees of freedom than you have now.

**Comment by lsf37** [comment]
I should add for @FinnZhang that the CDT is not necessarily only one global tree. It is a set of global trees, because the initial objects (initial thread, initial CNode, etc) do not have a parent. The set of initial objects form the roots of the set of the global CDTs.

The main operations that modify the CDT are `copy`, `retype`, `delete`, and `revoke`. Note that you can `delete` a parent of a cap without deleting the cap (`revoke` is the one that deletes all children, `delete` is usually only a single cap unless that cap is the last cap to an object). This means, if you have an initial Untyped (without parent) that you want to split into two completely separate subsystems that have no links to each other, you can retype that Untyped into two new Untypeds and delete the original. You now have two new CDT roots from which you can spawn separated subsystems.

**Comment by FinnZhang** [comment]
@lsf37 Thanks for your reply. Your answer made me understand CDT more deeply.
>  you can retype that Untyped into two new Untypeds and delete the original. You now have two new CDT roots from which you can spawn separated subsystems.

If I delete the original Untyped and then delete the two retyped Untypeds , Which Untyped the memory used by the two Untypeds will belong to? That is, after delete orginal Untyped and two retyped Untypes, which Untyped should use for the original Untyped‘s memory? Thank you.

**Comment by lsf37** [comment]
> If I delete the original Untyped and then delete the two retyped Untypeds , Which Untyped the memory used by the two Untypeds will belong to? That is, after delete orginal Untyped and two retyped Untypes, which Untyped should use for the original Untyped‘s memory? Thank you

Assuming there are no additional children of the new Untypeds, you will then then have deleted all caps to that memory and it becomes inaccessible. The situation would be as if you had deleted the original Untyped without ever creating anything from it. If the two new caps still do have children (from further `retype` or `copy`), those children become the new roots

**Comment by FinnZhang** [comment]
@lsf37 Thank you so much. 
Thanks all for helping me out.
