### ISSUE TITLE
thread can not suspend itself?

### ISSUE THREAD

**Issue by Makebug** [seL4/seL4#870]
thread can not suspend itself? @kent-mcleod @lsf37 
if NODE_STATE(ksCurThread) == target thread 
resume a suspend thread will failed
![image](https://user-images.githubusercontent.com/16549608/173588138-00d3d8c2-6d8e-494b-b094-c480452d10e2.png)

**Comment by lsf37** [comment]
It's not intended that a thread should suspend itself, but it looks like it could be made to work relatively easily if we allow `Restart` in that `if`. I haven't checked through all consequences of that, but I don't think it'd break anything, because we're setting the thread state to `Inactive` anyway just afterwards. (Not setting it to `Restart` in the first place should have the same effect in this specific case. It would violate the general pattern for invocations, but that would be fine here.)

In general it is *not* a property that a thread can be suspended and restarted and be expected to work again. This only works under fairly special circumstances (I haven't checked, but I would expect it to work if the suspended thread was just in state Running and not interacting with other threads -- anything involving any other thread state will have larger consequences like cancelling IPC etc). It is definitely not an opereration that should be used for user-level scheduling or similar applications. It's more an operation to tear down and set up threads, so the expectation is that the current thread would not do that to itself and then later want to run again. But I can see that the current thread would at least theoretically be in a position to make sure it is in a state that can be restarted, so I'd be up for tweaking the API for this case.

**Comment by kent-mcleod** [comment]
Threads can suspend themselves. This is often used when a thread has finished executing  and there's no other way for it to signal that it's done. Suspending itself is a better option compared to spinning in a seL4_Yield loop. This is what sel4test does: https://github.com/seL4/sel4test/blob/master/apps/sel4test-driver/src/main.c#L591-L594

**Comment by lsf37** [comment]
So do we get the right `RestartPC` for that? Because it does look like the code will pick `FaultIP` to restart the thread, not the current `PC`. If they happen to be equal, everything is fine, but I don't see that it would be guaranteed.

**Comment by kent-mcleod** [comment]
> So do we get the right `RestartPC` for that? Because it does look like the code will pick `FaultIP` to restart the thread, not the current `PC`. If they happen to be equal, everything is fine, but I don't see that it would be guaranteed.
> 
> Edit: actually, the example you link to is exactly what I meant, i.e. it is used for the thread to completely stop, not to be restarted at some point in the future. That application is fine and works. What I think doesn't work (and doesn't work in general for any thread) is the current thread suspending itself and then expecting to continue running in the same state when restarted. But there are some cases where that can work and we could add one more here.

I believe that the current design assumes that threads are adjusted (where adjusted includes seL4_TCB_Suspend, seL4_TCB_Write_Registers, seL4_TCB_ReadRegisters and potentially others) as part of a fault handling operation and so are blocked on an EP.  It's up to the user to adjust the program counter manually if the TCB needs to be advanced to the next instruction, otherwise it will restart and reattempt the fault instruction. 

The expected behavior if a thread suspends itself and is later resumed will be that it will restart on the instruction for the syscall that suspends itself.  If you want to advance the thread to the next instruction then it will need the PC to be updated.

There may be a need to relook at how this is designed though.  For example when an interrupt occurs, the FaultIP is still saved as the instruction before the NextIP. However this doesn't really make sense as the thread isn't faulting or performing a syscall.

**Comment by Makebug** [comment]
> So do we get the right `RestartPC` for that? Because it does look like the code will pick `FaultIP` to restart the thread, not the current `PC`. If they happen to be equal, everything is fine, but I don't see that it would be guaranteed.
> 
> Edit: actually, the example you link to is exactly what I meant, i.e. it is used for the thread to completely stop, not to be restarted at some point in the future. That application is fine and works. What I think doesn't work (and doesn't work in general for any thread) is the current thread suspending itself and then expecting to continue running in the same state when restarted. But there are some cases where that can work and we could add one more here.

I try to add some code on dynamic-2 example, and found a issue 

1. Create a thread thread-2
2. resume thread-2
3. suspend initial thread
4. ![image](https://user-images.githubusercontent.com/16549608/173715755-04bda2dd-3e21-4f2e-be5f-f5750a07e0dd.png)
5. thread-2 resume initial thread
6. ![image](https://user-images.githubusercontent.com/16549608/173715877-3eae5062-ab61-4919-a6ee-77f1b3717a9a.png)

it can not resume initial thread and i found it will suspend initial thread again

**Comment by kent-mcleod** [comment]
> it can not resume initial thread and i found it will suspend initial thread again

You need to add something like the following:
```
    seL4_UserContext context;
    int res = seL4_TCB_ReadRegisters(simple_get_tcb(&env.simple), 1, 0, (sizeof(seL4_UserContext) / sizeof(seL4_Word)), &context );
    ZF_LOGF_IF(res, "Could not read registers");
    /* When you call write registers or suspend on a thread, seL4 changes it to be restarted.
        The eip needs to be incremented so that the target thread is resumed correctly instead of recalling the invocation. */
    seL4_Word pc = sel4utils_get_instruction_pointer(context);
    sel4utils_set_instruction_pointer(&context, pc + ARCH_SYSCALL_INSTRUCTION_SIZE);
    res = seL4_TCB_WriteRegisters(simple_get_tcb(&env.simple), 1, 0, (sizeof(seL4_UserContext) / sizeof(seL4_Word)), &context );
    ZF_LOGF_IF(res, "Could not write registers");
```

**Comment by mikeyang2022** [comment]
> > it can not resume initial thread and i found it will suspend initial thread again
> 
> You need to add something like the following:
> 
> ```
>     seL4_UserContext context;
>     int res = seL4_TCB_ReadRegisters(seL4_CapInitThreadTCB, 1, 0, (sizeof(seL4_UserContext) / sizeof(seL4_Word)), &context );
>     ZF_LOGF_IF(res, "Could not read registers");
>     /* When you call write registers or suspend on a thread, seL4 changes it to be restarted.
>         The eip needs to be incremented so that the target thread is resumed correctly instead of recalling the invocation. */
>     seL4_Word pc = sel4utils_get_instruction_pointer(context);
>     sel4utils_set_instruction_pointer(&context, pc + ARCH_SYSCALL_INSTRUCTION_SIZE);
>     res = seL4_TCB_WriteRegisters(seL4_CapInitThreadTCB, 1, 0, (sizeof(seL4_UserContext) / sizeof(seL4_Word)), &context );
>     ZF_LOGF_IF(res, "Could not write registers");
> ```

Yes, I tried and confirm the code can work to resume the thread that suspended by itself.
However, it seems much confusing why that detail should be exposed to user.
Is that the kernel responsible for that everything to help restore the thread?

**Comment by Makebug** [comment]
Is there a problem with this modification ? :) :) :) 
![image](https://user-images.githubusercontent.com/16549608/173720634-654b3453-c2a3-488b-a89e-942f3801ad0b.png)

**Comment by Makebug** [comment]
How about this modify
![image](https://user-images.githubusercontent.com/16549608/173721733-b2c8a359-1024-4244-9f3a-e90135acf40c.png)

**Comment by kent-mcleod** [comment]
> However, it seems much confusing why that detail should be exposed to user.
> Is that the kernel responsible for that everything to help restore the thread?

Kernel invocations are modeled as IPC messages from the calling thread to the kernel. If the target thread being suspended was in the middle of any other kernel operation, then the result of a suspend/resume operation would be to restart the kernel operation. When a thread suspends itself, the kernel sets it to inactive which means that it can no longer have any kernel operations in place and so the reply message part of the invocation IPC cannot be completed. Restarting the thread at the start of the operation if it is resumed is consistent with all other kernel operations and the IPC invocation model. Wishing to advance the thread over the kernel operation to resume after the operation has completed is a different policy that can be implemented from user level currently.

**Comment by mikeyang2022** [comment]
> There may be a need to relook at how this is designed though. For example when an interrupt occurs, the FaultIP is still saved as the instruction before the NextIP. However this doesn't really make sense as the thread isn't faulting or performing a syscall.
@kent-mcleod 

I notice that thread always saves ```FaultIP``` and ```NextIP``` in currently design. As you said, the ```FaultIP``` is meaningless when kernel proceess **interrupts** because the ```NextIP``` is the real program counter the thread should go. Besides, so does ```FaultIP``` and ```NextIP``` of **syacall**.  ```FaultIP``` is vital to **fault** but ```NextIP``` is redundant. 
So in brief, a single ```PC``` field is enough for **intterrupts, syscall and fault** in my mind. The ```PC``` means the thread will go there after kernel operation complete.

**Comment by kent-mcleod** [comment]
> However it plays the role of seL4_TCB_Resume actually interestingly. In other words, seL4_TCB_Resume is not needed any more here.

There's an explicit parameter to `seL4_TCB_WriteRegisters` that controls whether the thread is resumed or left suspended. It's an optimization to save the additional call cost to `seL4_TCB_Resume`.

>  So in brief, a single PC field is enough for intterrupts, syscall and fault in my mind. The PC means the thread will go there after kernel operation complete.

Most operations potentially need both values. 
- For a syscall, any invocation can cause a lookup fault which can generate a CapFault and the `FaultIP` is needed. 
- For a fault, certain fault types such as `seL4_Fault_UnknownSyscall`, `seL4_Fault_Timeout` and `seL4_Fault_UserException` resume the thread with NextIP if the `label` in the fault reply message is non-zero.

**Comment by kent-mcleod** [comment]
Closing as stale/resolved.
