### ISSUE TITLE
CNodes should have write rights

### ISSUE THREAD

**Issue by Indanz** [seL4/seL4#943]
With a multi-level CSpace layout, it's impossible to give access to a CNode's caps without giving access to the CNode cap itself.

Every `seL4_CNode_*` operation should check and require write rights. Usually you don't want everyone with access to a non-CNode cap to be able to revoke or delete it.

(See also comments at #940.)

Update:
- To do CNode operations the cap to the CNode must be at the edge, so intermediate CNode caps can't be used to control themselves, so the above statement is not true.
- However, write access is still needed to distinguish between read-only CNodes used as a source and destination CNodes. Practically this is mostly needed to map page caps multiple times for shared memory.

**Comment by lsf37** [comment]
I think you are right, having a `write` right (as opposed to  `read` and `write`) does make sense and we should probably reconsider this design choice.

**Comment by mbrcknl** [comment]
> With a multi-level CSpace layout, it's impossible to give access to a CNode's caps without giving access to the CNode cap itself.

IIUC, this is not quite true. To perform a `seL4_CNode_*` invocation, you need to invoke a CNode cap, and it's impossible to identify a CNode for invocation without resolving all bits of the capability reference. Therefore, only CNode caps at the edge of the CSpace are available for `seL4_CNode_*` invocations. Once you have identified a CNode in this way, the `seL4_CNode` invocations then allow you to treat the identified CNode as the root of a CSpace, and allow you to modify any slot in that CSpace using the `index` and `depth` arguments.

Now, there is a common approach to setting up a thread's CSpace that includes a guarded cap pointing back to the root of the thread's own CSpace, to make the *root* of the thread's CSpace available at the *edge* of the same CSpace. It's this cap that gives a thread write access to every slot in its own CSpace. If you omit this cap, the thread cannot modify its own CSpace.

This means there is already a way to give a thread the ability to modify part of its own CSpace, while preventing it from modifying other parts: Make the guarded cap point to only the subspace that the thread should be allowed to modify. In the picture below, the numbers are guard bits, where `n` satisfies:

`1 + r + n + r = w`

where `r` is the radix of the left-hand CNode, and `w` is the word size. The thread can modify the left-hand sub-tree using `seL4_CNode_*` on slot zero, but can't modify the right-hand sub-tree.

![cspace-new drawio](https://user-images.githubusercontent.com/1797886/199372772-eebeaa6f-a238-42b7-932a-50e81720da1c.svg)

However, there are some down-sides to using the existing mechanisms to partially restrict access to the CSpace, so it might still make sense to add a write permission to CNode caps:
- The thread can't configure other threads with the same CSpace, because `seL4_TCB_SetSpace` has the same requirements for addressing the root of the CSpace.
- Obviously reduces the usable depth of the CSpace by one bit, and makes the calculation of slot references a bit more complicated.

**Comment by Indanz** [comment]
Thanks @mbrcknl for clearing this up! I should have double checked before opening this issue. I missed the important "Must be at a depth equivalent to the wordsize." bit in the manual for CNode operations. I assumed the `depth` parameter was used for resolving the CNode, as that is the ambiguous one, while all operations are limited to slots within the CNode, so the depth of the final slot could be known.

Strangely enough, doing a `seL4_CNode_Delete()` on a CNode cap not at the edge seems to silently fail: That is, there are no errors, but nothing was actually deleted either. Even with debugging on there is no output at all. Looking at `decodeInvocation`, doing any CNode operation on a notification object actually just sends a signal!

> This means there is already a way to give a thread the ability to modify part of its own CSpace, while preventing it from modifying other parts: Make the guarded cap point to only the subspace that the thread should be allowed to modify.

With this in mind I retract my proposal, as it's not needed.

> If we do add a write bit to the CNode cap permissions, we should make sure to identify all such restrictions implied by the current mechanism, to make sure we don't just end up duplicating the limitations of the current mechanism.

Agreed.

**Comment by Indanz** [comment]
My colleague Peter had a smart idea how to get an edge CNode cap while it's in the top CNode in a multi-level CSpace: Just make sure that the guard size and bits are correct and make sure resolving the CPtr ends at the CNode cap. Resolving it would give for instance the following path:

`root CNode -> cap to root (bits remaining, follow it) -> root -> cap to root (all bits resolved, so now it's an edge node).`

So it seems possible to put the app controlled CNode cap `n` in the root-controlled CNode instead of the extra indirection in your example.

E.g. root CNode 24 bit guard 0x000001, 8 bit radix. Cap to root in slot 2, with 24 bit guard 0x0. Then to access the cap to root as an edge node, you use CPtr 0x0000010200000002, (And if you put it in slot 0 the address is as expected.)

With this trick you don't lose 1 bit CSpace.

As a side-note, the CSpace documentation in the manual is not very clear. Notably, the diagrams are misleading, in that every cap has its own guard value and size, it's not part of the CNode itself. If every CNode only has one reference there is no difference, but there is if there are multiple ones, including back references.

**Comment by Indanz** [comment]
Actually MEP's use case can't be handled properly without CNode permissions. We have a two-stage loader setup where a minimal rootserver loads and runs the application, and gives it access to untyped memory and all the other caps it needs to spawn more tasks and do what needs to be done. So the application needs to:

- Have a CNode it can create and copy caps to.
- Needs access to a bunch of "read-only" caps it should not be able to delete or revoke or move away.
- However, it does need to copy some of those caps to create multiple memory mappings (needed for shared memory) or to give spawned tasks access to them.
- CNode operations need access to the source CNode too, not only the destination.

Currently there is a theoretical chance that the application messes up its CSpace, so when reloading the application it's not guaranteed all state is back to a known working state.

What is missing is to give access to the app's CNode without giving it power to mess up the root controlled CNode. So write access on a CNode should allow to use it as a destination in a CNode operation, and read access allows it to be used as a source CNode.

CNode rights should only be checked for CNode operations and UntypedRetype.

**Comment by Indanz** [comment]
Thinking this through it seems very hard to get all details correct, so closing this issue again.
